#
# @(#)Makefile	1.3 03/01/23 11:04:17
#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL.  Use is subject to license terms.
#


all:
	cd dbx; $(MAKE) all
	cd proc; $(MAKE) all

clean:
	cd dbx; $(MAKE) clean
	cd proc; $(MAKE) clean
