#
# @(#)Makefile	1.25 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../..

PACKAGE = org.omg.CosNaming
PRODUCT = org

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
include ../CosNaming_java.gmk

FILES_java = $(NS_GENERATED_java) $(LEGACY_FILES_java)

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
