'\" t
.\" @(#)serialver.1 1.10 00/06/13 SMI;
.\" Copyright 2003 Sun Microsystems, Inc. All rights reserved.
.\" Copyright 2003 Sun Microsystems, Inc. Tous droits réservés.
.\" 
.TH serialver 1 "Apr 23 2001"
.\" .TH serialver 1 "12 May 2000"
.SH NAME
serialver \- serial version command
.\"
.\" This comment retained for historical purposes only:
.\"  This document was created by saving an HTML file as text
.\"  from the JavaSoft web site:
.\" 
.\" http://java.sun.com/j2se/1.4/docs/tooldocs/tools.html
.\" 
.\"  and adding appropriate troff macros.
.\" 
.SH SYNOPSIS
.B serialver 
[
.B \-show
] [
.I classnames
] [
.B \-J
]
.SH DESCRIPTION
.IX "serial version command" "" "serial version command \(em \fLserialver\fP"
.IX "serialver" "" "\fLserialver\fP \(em serial version command"
The 
.B serialver 
command returns the
.B serialVersionUID
for one or more classes in
a form suitable for copying into an evolving class.
When invoked
with no arguments, it prints a usage line.
.SH OPTIONS
The following options are supported:
.TP 15
.B \-show
Displays a simple user interface.
Enter the full class name
and press either the Enter key or the Show button to display
the
.BR serialVersionUID .
.SH OPERANDS
.TP 15 
.I classnames
One or more class names.
.TP 15
.B J " option"
Pass
.I option
to the Java virtual machine, where
.I option
is one of the options described on the man page for the
java application launcher, java(1). For example,
.I \-J-Xms48m
sets the startup memory to 48 megabytes. It is a common convention for
.B \-J
to pass options to the underlying virtual machine.

.SH SEE ALSO
.LP
See (or search
.BR java.sun.com )
for the following:
.TP 5
.B java.io.ObjectStreamClass @
http://java.sun.com/j2se/1.4/docs/api/java/io/ObjectStreamClass.html
