#
# @(#)Makefile	1.8 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D gui sources
#

BUILDDIR = ../../../..
DEMONAME = gui
include $(BUILDDIR)/common/Defs.gmk
include FILES.gmk
include ../DemoJava2D.gmk
