#
# @(#)Makefile	1.19 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../../../..

PACKAGE = com.sun.corba.se.ActivationIDL
PRODUCT = org

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#

include ../ActivationIDL_java.gmk

FILES_java=$(ActivationIDL_java)

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
