#
# @(#)Makefile	1.8 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build the Persistent CosNaming Classes
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.internal.PCosNaming
PRODUCT = PCosNaming
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
include FILES_java.gmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
