#
# @(#)Makefile	1.4 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

# @(#)Makefile	1.4 03/01/23

default:
	javac -d . *.java

clean:
	rm -rf javasoft
