#
# @(#)Makefile	1.17 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the Table demo.
#

BUILDDIR = ../../..
DEMONAME = TableExample
include ../DemoSwing.gmk
