#
# @(#)Makefile	1.9 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D demos/Mix sources
#

BUILDDIR = ../../../../..
DEMONAME = demos/Mix
PKGPATH = $(DEMODST)/$(DEMONAME)
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(PKGPATH)/Balls.java \
             $(PKGPATH)/BezierScroller.java \
             $(PKGPATH)/JavaMedia.java \
             $(PKGPATH)/Stars3D.java


DEMO_dirs  = $(DEMODST) \
             $(DEMODST)/java2d/demos \
             $(DEMODST)/java2d/demos/Mix

include ../../DemoJava2D.gmk
