#
# @(#)Makefile	1.5 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the SwingSet2 demo.
#

BUILDDIR = ../../..
DEMONAME = SwingSet2
include ../DemoSwing.gmk
