#
# @(#)Makefile	1.8 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D demos/Colors sources
#

BUILDDIR = ../../../../..
DEMONAME = demos/Colors
PKGPATH = $(DEMODST)/$(DEMONAME)
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(PKGPATH)/BullsEye.java \
             $(PKGPATH)/ColorConvert.java \
             $(PKGPATH)/Rotator3D.java


DEMO_dirs  = $(DEMODST) \
             $(DEMODST)/java2d/demos \
             $(DEMODST)/java2d/demos/Colors

include ../../DemoJava2D.gmk
