#
# @(#)Makefile	1.8 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D demos/Lines sources
#

BUILDDIR = ../../../../..
DEMONAME = demos/Lines
PKGPATH = $(DEMODST)/$(DEMONAME)
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(PKGPATH)/Caps.java \
             $(PKGPATH)/Dash.java \
             $(PKGPATH)/Joins.java \
             $(PKGPATH)/LineAnim.java

DEMO_dirs  = $(DEMODST) \
             $(DEMODST)/java2d/demos \
             $(DEMODST)/java2d/demos/Lines

include ../../DemoJava2D.gmk

