#
# @(#)Makefile	1.7 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

# makefile for building JPEG classes

BUILDDIR = ../../..
PACKAGE = com.sun.image.codec.jpeg
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk


#
# Files
#
include FILES_java.gmk


#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

