#
# @(#)Makefile	1.14 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building java.beans.*
#

BUILDDIR = ../..
PACKAGE = java.beans
PRODUCT = java
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
include FILES_java.gmk

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
