#
# @(#)Makefile	1.10 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR     = ../../..
PACKAGE      = dtbuilder
PRODUCT      = javax/swing/html
CLASSDESTDIR = $(TMPDIR)/dtdgenclasses
include $(BUILDDIR)/common/Defs.gmk

html32dtd: swing-html32dtd

include SwingHTML32DTD.gmk
