#
# @(#)Makefile	1.7 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../../../../..

PACKAGE = com.sun.corba.se.internal.Interceptors
PRODUCT = com

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#

include FILES_java.gmk

#
# Include
#

include $(BUILDDIR)/common/Classes.gmk

