/*
 * @(#)Activator_fr.java	1.53 03/05/19
 *
 * Copyright 2003 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package sun.plugin.resources;

import java.util.ListResourceBundle;
import java.awt.event.KeyEvent;
/**
 * French version of Activator strings.
 *
 * @author Jerome Dochez
 */

public class Activator_fr extends ListResourceBundle {

    public Object[][] getContents() {
         return contents;
    }

    static final Object[][] contents = {
	{ "panel.caption", "Panneau de commande Java Plug-in(TM)" }, 
        { "product_name", "Plug-in Java(TM)" },
        { "version", "Version" },
        { "default_vm_version", "Version implicite de la machine virtuelle" },
        { "using_jre_version", "Utilisation de la version JRE" },
        { "user_home_dir", "R\u00e9pertoire d'accueil de l'utilisateur" },
        { "user_overriden_browser", "L'utilisateur a \u00e9cras\u00e9 les param\u00e8tres de proxy du navigateur." },
        { "proxy_configuration", "Configuration du proxy : " },
        { "browser_config", "Configuration du proxy du navigateur" },
        { "auto_config", "Configuration automatique du proxy" },
        { "manual_config", "Configuration manuelle" },
        { "no_proxy", "Aucun proxy" },
        { "proxy_is", "Proxy : " },
        { "proxy_override_is", "Remplacement du proxy : " },
        { "loading", "Chargement de {0}" },
        { "java_applet", "Applet Java" },
        { "failed", "Echec de chargement de l'Applet Java..." },
        { "image_failed", "Echec de cr\u00e9ation d'une image d\u00e9finie par l'utilisateur.  V\u00e9rifiez le nom de fichier de l'image." },
        { "java_bean", "JavaBeans" },
        { "java_not_enabled", "Java n'est pas activ\u00e9" },
        { "exception", "Exception : {0}" },

    	{ "net.connect.no_proxy", "Connexion {0} sans proxy" },
    	{ "net.connect.proxy_is", "Connexion {0} avec proxy={1}" },

        { "bean_code_and_ser", "CODE et JAVA_OBJECT ne peuvent pas \u00eatre d\u00e9finis \u00e0 la fois pour Bean " },
        { "status_applet", "Applet {0} [1}" },

        // Resources associated with SecurityManager print Dialog:
	{ "print.caption", "Confirmation requise - Impression" },
        { "print.message", new String[]{
		"<html><b>Demande d'impression</b></html>L'applet souhaite imprimer. Voulez-vous continuer ?"}},
        { "print.checkBox", "Ne plus afficher cette bo\u00eete de dialogue" }, 
      { "print.buttonYes", "Oui" },
        { "print.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "print.buttonNo", "Non" },
        { "print.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        
	{ "https_dialog.caption", "Avertissement - HTTPS" },
	{ "https_dialog.text", "<html><b>Discordance du nom d''h\u00f4te</b></html>Le nom d''h\u00f4te figurant dans le certificat de s\u00e9curit\u00e9 du serveur ne correspond pas au nom du serveur." 
					    + "\n\nNom d''h\u00f4te de l''URL : {0}"
					    + "\nNom d''h\u00f4te du certificat : {1}"
					    + "\n\nVoulez-vous continuer ?"},
	{ "https_dialog.unknown.host", "H\u00f4te inconnu" },

	{ "security_dialog.caption", "Avertissement - S\u00e9curit\u00e9" },
        { "security_dialog.text0", "Voulez-vous accepter l''applet sign\u00e9 distribu\u00e9 par \"{0}\"?"
        			    + "\n\nAuthenticit\u00e9 de l''\u00e9diteur v\u00e9rifi\u00e9e par \"{1}\""},
	{ "security_dialog_https.text0", "Acceptez-vous le certificat du site Web \"{0}\" en vue d''un \u00e9change d''informations crypt\u00e9es ?"
				    + "\n\nAuthenticit\u00e9 de l''\u00e9diteur v\u00e9rifi\u00e9e par \"{1}\""},	
        { "security_dialog.text1", "\nAttention : \"{0}\" atteste que ce contenu est \ns\u00fbr. Vous ne devriez accepter ce contenu que si vous estimez que \"{1}\" est digne de confiance.\n\n" },
    	{ "security_dialog.unknown.issuer", "Emetteur inconnu" },
	{ "security_dialog.unknown.subject", "Sujet inconnu" },
	{ "security_dialog.certShowName", "{0}({1})" },
	{ "security_dialog.rootCANotValid", "Le certificat de s\u00e9curit\u00e9 a \u00e9t\u00e9 \u00e9mis par une soci\u00e9t\u00e9 qui n'est pas digne de confiance." },
	{ "security_dialog.rootCAValid", "Le certificat de s\u00e9curit\u00e9 a \u00e9t\u00e9 \u00e9mis par une soci\u00e9t\u00e9 qui est digne de confiance." },
	{ "security_dialog.timeNotValid", "Le certificat de s\u00e9curit\u00e9 a expir\u00e9 ou n'est pas encore valide." },
	{ "security_dialog.timeValid", "Le certificat de s\u00e9curit\u00e9 n'a pas expir\u00e9 et est encore valide." },
	{ "security_dialog.buttonAlways", "Toujours" },
        { "security_dialog.buttonAlways.acceleratorKey", new Integer(KeyEvent.VK_T)},
	{ "security_dialog.buttonYes", "Oui" },
	{ "security_dialog.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "security_dialog.buttonNo", "Non" },
	{ "security_dialog.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "security_dialog.buttonViewCert", "Plus de d\u00e9tails" },	
        { "security_dialog.buttonViewCert.acceleratorKey", new Integer(KeyEvent.VK_P)},
        
	{ "cert_dialog.caption", "D\u00e9tails - Certificat" },
	{ "cert_dialog.certpath", "Chemin d'acc\u00e8s du certificat" },
	{ "cert_dialog.field.Version", "Version" },
	{ "cert_dialog.field.SerialNumber", "Num\u00e9ro de s\u00e9rie" },
	{ "cert_dialog.field.SignatureAlg", "Algorithme de signature" },
	{ "cert_dialog.field.Issuer", "Emetteur" },
	{ "cert_dialog.field.EffectiveDate", "Date effective" },
	{ "cert_dialog.field.ExpirationDate", "Date d'expiration" },
	{ "cert_dialog.field.Validity", "Validit\u00e9" },
	{ "cert_dialog.field.Subject", "Sujet" },
	{ "cert_dialog.field.Signature", "Signature" },
	{ "cert_dialog.field", "Champ" },
	{ "cert_dialog.value", "Valeur" },

        { "cert_dialog.close", "Fermer" },
	{ "cert_dialog.close.acceleratorKey", new Integer(KeyEvent.VK_F) },

	{ "net.authenticate.caption", "Mot de passe requis - Gestion de r\u00e9seau"},
	{ "net.authenticate.label", "<html><b>Entrez vos nom d'utilisateur et mot de passe :</b></html>"},
	{ "net.authenticate.resource", "Ressource :" },
	{ "net.authenticate.username", "Nom d'utilisateur :" },
	{ "net.authenticate.password", "Mot de passe :" },
	{ "net.authenticate.firewall", "Pare-feu :" },
	{ "net.authenticate.realm", "Domaine :" },
	{ "net.authenticate.scheme", "Plan :" },
	{ "net.authenticate.unknownSite", "Site inconnu" },

        { "console.caption", "Console Java" },
        { "console.clear", "Effacer" },
        { "console.clear.acceleratorKey", new Integer(KeyEvent.VK_E)},
        { "console.close", "Fermer" },
        { "console.close.acceleratorKey", new Integer(KeyEvent.VK_F) },
        { "console.copy", "Copier" },
        { "console.copy.acceleratorKey", new Integer(KeyEvent.VK_C) },

	{ "optpkg.cert_expired", "<html><b>Le certificat a expir\u00e9</b></html>L'installation du package facultatif a \u00e9t\u00e9 abandonn\u00e9e.\n" },
	{ "optpkg.cert_notyieldvalid", "<html><b>Le certificat n'est pas valide</b></html>L'installation du package facultatif a \u00e9t\u00e9 abandonn\u00e9e.\n" },
	{ "optpkg.cert_notverify", "<html><b>Le certificat n'a pas \u00e9t\u00e9 v\u00e9rifi\u00e9</b></html>L'installation du package facultatif a \u00e9t\u00e9 abandonn\u00e9e.\n" },
	{ "optpkg.general_error", "<html><b>Exception g\u00e9n\u00e9rale</b></html>L'installation du package facultatif a \u00e9t\u00e9 abandonn\u00e9e.\n" },
	{ "optpkg.caption", "Avertissement - Package facultatif" },
	{ "optpkg.installer.launch.wait", "<html><b>Installation du package facultatif en cours</b></html>Cliquez sur OK pour continuer le chargement de l'applet apr\u00e8s l'arr\u00eat du programme d'installation du package facultatif.\n" },
	{ "optpkg.installer.launch.caption", "Installation en cours - Package facultatif"},
	{ "optpkg.prompt_user.new_spec.text", "<html><b>Demande de t\u00e9l\u00e9chargement</b></html>L''applet requiert une version plus r\u00e9cente (sp\u00e9cification {0}) du package facultatif \"{1}\" \u00e0 partir de {2}\n\nVoulez-vous continuer ?" },
	{ "optpkg.prompt_user.new_impl.text", "<html><b>Demande de t\u00e9l\u00e9chargement</b></html>L''applet requiert une version plus r\u00e9cente (impl\u00e9mentation {0}) du package facultatif \"{1}\" \u00e0 partir de {2}\n\nVoulez-vous continuer ?" },
	{ "optpkg.prompt_user.new_vendor.text", "<html><b>Demande de t\u00e9l\u00e9chargement</b></html>L''applet requiert ({0})du package facultatif \"{1}\" {2} \u00e0 partir de {3}\n\nVoulez-vous continuer ?" },
	{ "optpkg.prompt_user.default.text", "<html><b>Demande de t\u00e9l\u00e9chargement</b></html>L''applet requiert l''installation du package facultatif \"{0}\" \u00e0 partir de {1}\n\nVoulez-vous continuer ?" },

	{ "rsa.cert_expired", "<html><b>Le certificat a expir\u00e9</b></html>Le code sera consid\u00e9r\u00e9 comme \u00e9tant non sign\u00e9.\n" },
	{ "rsa.cert_notyieldvalid", "<html><b>Le certificat n'est pas valide</b></html>Le code sera consid\u00e9r\u00e9 comme \u00e9tant non sign\u00e9.\n" },
	{ "rsa.general_error", "<html><b>Le certificat n'a pas \u00e9t\u00e9 v\u00e9rifi\u00e9</b></html>Le code sera consid\u00e9r\u00e9 comme \u00e9tant non sign\u00e9.\n" },

	{ "usability.confirmDialogTitle", "Confirmation requise - Java" },
	{ "usability.inputDialogTitle", "Informations requises - Java" },
	{ "usability.messageDialogTitle", "Message - Java" },
	{ "usability.exceptionDialogTitle", "Erreur - Java" },
	{ "usability.optionDialogTitle", "Option - Java" },
	{ "usability.aboutDialogTitle", "\u00c0 propos de - Java" },
        { "usability.confirm.yes", "Oui" },
        { "usability.confirm.yes.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "usability.confirm.no", "Non" },
        { "usability.confirm.no.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "usability.moreInfo", "Plus de d\u00e9tails" },	
        { "usability.moreInfo.acceleratorKey", new Integer(KeyEvent.VK_P)},
        { "usability.lessInfo", "Moins de d\u00e9tails" },	
        { "usability.lessInfo.acceleratorKey", new Integer(KeyEvent.VK_M)},
	{ "usability.java.home.link", "http://www.java.com" },

	{ "usability.general_error", "<html><b>Exception g\u00e9n\u00e9rale</b></html>" },
	{ "usability.net_error", "<html><b>Exception de gestion de r\u00e9seau</b></html>" },
	{ "usability.security_error", "<html><b>Exception de s\u00e9curit\u00e9</b></html>" },
	{ "usability.ext_error", "<html><b>Exception de package facultatif</b></html>" },

        { "usability.menu.show_console", "Afficher la console Java" },
        { "usability.menu.hide_console", "Masquer la console Java" },
        { "usability.menu.about", "\u00c0 propos du plug-in Java" },
        { "usability.menu.copy", "Copier" },
	{ "usability.menu.open_console", "Ouvrir la console Java" },
	{ "usability.menu.about_java", "\u00c0 propos de Java(TM)" },

	{ "proxy.error_caption", "Erreur - Configuration du proxy" },
	{ "proxy.prefsfile.nsreg_error", "<html><b>Impossible de r\u00e9cup\u00e9rer les param\u00e8tres du proxy</b></html>Basculement vers une autre configuration du proxy.\n" },

	{ "cache.error.text", "<html><b>Erreur de mise en cache</b></html>Impossible de stocker ou de mettre \u00e0 jour des fichiers dans le cache." },
	{ "cache.error.caption", "Erreur - Cache" },
	{ "cache.version_format_error", "{0} n''a pas le format xxxx.xxxx.xxxx.xxxx, o\u00f9 x est un nombre hexad\u00e9cimal" },
		{ "cache.version_attrib_error", "Le nombre d'attributs sp\u00e9cifi\u00e9 dans 'cache_archive' ne correspond pas \u00e0 celui de 'cache_version'" },
	{ "cache.header_fields_missing", "L'heure de la derni\u00e8re modification et/ou le d\u00e9lai d'expiration n'est pas disponible.  Le fichier Jar ne sera pas mis en cache."},

		{ "applet.progress.load", "Chargement de l'applet..." },
		{ "applet.progress.init", "Initialisation de l'applet..." },
		{ "applet.progress.start", "D\u00e9marrage de l'applet..." },
		{ "applet.progress.stop", "Arr\u00eat de l'applet..." },
		{ "applet.progress.destroy", "Destruction de l'applet..." },
		{ "applet.progress.dispose", "Elimination de l'applet..." },
		{ "applet.progress.quit", "Sortie de l'applet..." },
		{ "applet.progress.stoploading", "Chargement arr\u00eat\u00e9..." },
		{ "applet.progress.interrupted", "Thread interrompu..." },
		{ "applet.progress.joining", "Jointure du thread d'applet..." },
		{ "applet.progress.joined", "Thread d'applet joint..." },
		{ "applet.progress.loadImage", "Chargement d'image " },
		{ "applet.progress.loadAudio", "Chargement audio " },
		{ "applet.progress.findinfo.0", "Recherche d'informations..." },
		{ "applet.progress.findinfo.1", "Termin\u00e9..." },
		{ "applet.progress.timeout.wait", "Attente de fin de d\u00e9lai..." },
		{ "applet.progress.timeout.jointing", "Jointure en cours..." },
		{ "applet.progress.timeout.jointed", "Jointure termin\u00e9e..." },


		{ "console.menu.text.top", "----------------------------------------------------\n" },
		{ "console.menu.text.c", "c:   effacer la fen\u00eatre de la console\n" },
		{ "console.menu.text.f", "f:   finaliser les objets de la file d'attente de finalisation\n" },
		{ "console.menu.text.g", "g:   lib\u00e9rer la m\u00e9moire\n" },
		{ "console.menu.text.h", "h:   afficher ce message d'aide\n" },
		{ "console.menu.text.j", "j: vider les donn\u00e9es jcov\n"},
		{ "console.menu.text.l", "l:   vider la liste de chargeurs de classes\n" },
		{ "console.menu.text.m", "m:   imprimer le relev\u00e9 d'utilisation de la m\u00e9moire\n" },
		{ "console.menu.text.o", "o:   d\u00e9clencher la consignation\n" },
		{ "console.menu.text.p", "p:   recharger la configuration du proxy\n" },
		{ "console.menu.text.q", "q:   masquer la console\n" },
		{ "console.menu.text.r", "r:   recharger la configuration des politiques\n" },
		{ "console.menu.text.s", "s:   vider les propri\u00e9t\u00e9s syst\u00e8me\n" },
		{ "console.menu.text.t", "t:   vider la liste des threads\n" },
	{ "console.menu.text.v", "v:   vider la pile des threads\n" },
		{ "console.menu.text.x", "x:   effacer le cache de chargeurs de classes\n" },
		{ "console.menu.text.0", "0-5: fixer le niveau de tra\u00e7age \u00e0 <n>\n" },
		{ "console.menu.text.tail", "----------------------------------------------------\n" },
		{ "console.done", "Termin\u00e9." },
		{ "console.trace.level.0", "Niveau de tra\u00e7age fix\u00e9 \u00e0 0 : aucun ... termin\u00e9." },
		{ "console.trace.level.1", "Niveau de tra\u00e7age fix\u00e9 \u00e0 1 : base ... termin\u00e9." },
		{ "console.trace.level.2", "Niveau de tra\u00e7age fix\u00e9 \u00e0 2 : base, r\u00e9seau ... termin\u00e9." },
		{ "console.trace.level.3", "Niveau de tra\u00e7age fix\u00e9 \u00e0 3 : base, r\u00e9seau, s\u00e9curit\u00e9 ... termin\u00e9." },
	    { "console.trace.level.4", "Niveau de tra\u00e7age fix\u00e9 \u00e0 4 : base, r\u00e9seau, s\u00e9curit\u00e9, ext ... termin\u00e9." },
		{ "console.trace.level.5", "Niveau de tra\u00e7age fix\u00e9 \u00e0 5 : base, r\u00e9seau, s\u00e9curit\u00e9, ext, connexion ... termin\u00e9." },
		{ "console.log", "Consignation : " },
		{ "console.completed", " .... termin\u00e9." },
		{ "console.dump.thread", "Vider la liste des threads...\n" },
	{ "console.dump.stack", "Vider la pile des threads ...\n" },
		{ "console.dump.properties", "Vider les propri\u00e9t\u00e9s syst\u00e8me...\n" },
		{ "console.clear.classloader", "Effacer le cache de chargeur de classes .... termin\u00e9." },
		{ "console.reload.policy", "Recharger la configuration des politiques" },
		{ "console.reload.proxy", "Recharger la configuration du proxy ...." },
		{ "console.gc", "Lib\u00e9rer la m\u00e9moire" },
		{ "console.finalize", "Finaliser les objets de la file d'attente de finalisation" },
		{ "console.memory", "M\u00e9moire : {0}K  Libre : {1}K  ({2}%)" },
		{ "console.jcov.error", "Erreur d'ex\u00e9cution de Jcov : Assurez-vous d'avoir pr\u00e9cis\u00e9 l'option jcov correcte\n"},
		{ "console.jcov.info", "Les donn\u00e9es Jcov ont \u00e9t\u00e9 vid\u00e9es\n"},

		{ "modality.register", "R\u00e9cepteur de modalit\u00e9s enregistr\u00e9" },
		{ "modality.unregister", "R\u00e9cepteur de modalit\u00e9s non enregistr\u00e9" },
		{ "modality.pushed", "Modalit\u00e9 empil\u00e9e" },
		{ "modality.popped", "Modalit\u00e9 d\u00e9sempil\u00e9e" },

		{ "progress.listener.added", "R\u00e9cepteur de progression ajout\u00e9 : {0}" },
		{ "progress.listener.removed", "R\u00e9cepteur de progression supprim\u00e9 : {0}" },

		{ "liveconnect.UniversalBrowserRead.enabled", "JavaScript : UniversalBrowserRead activ\u00e9" },
		{ "liveconnect.java.system", "JavaScript : appel du code syst\u00e8me Java" },
		{ "liveconnect.same.origin", "JavaScript : appelant et appel\u00e9 ont la m\u00eame origine" },
		{ "liveconnect.default.policy", "JavaScript : politique de s\u00e9curit\u00e9 par d\u00e9faut = {0}" },
		{ "liveconnect.UniversalJavaPermission.enabled", "JavaScript : UniversalJavaPermission activ\u00e9" },
		{ "liveconnect.wrong.securitymodel", "Le mod\u00e8le de s\u00e9curit\u00e9 de Netscape n'est plus pris en charge.\n"
		                         + "Migrez vers le mod\u00e8le de s\u00e9curit\u00e9 Java 2.\n" },

		{ "jpicertstore.cert.loading", "Chargement des certificats JPI depuis {0}" },
		{ "jpicertstore.cert.loaded", "Certificats JPI charg\u00e9s depuis {0}" },
		{ "jpicertstore.cert.saving", "Enregistrement des certificats JPI dans {0}" },
		{ "jpicertstore.cert.saved", "Certificats JPI enregistr\u00e9s dans {0}" },
		{ "jpicertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats permanents JPI", },
		{ "jpicertstore.cert.added", "Certificat ajout\u00e9 comme alias {0} dans la zone de stockage des certificats permanents JPI " },
		{ "jpicertstore.cert.removing", "Suppression du certificat dans la zone de stockage des certificats permanents JPI" },
		{ "jpicertstore.cert.removed", "Certificat supprim\u00e9 comme alias {0} dans la zone de stockage des certificats permanents JPI " },
		{ "jpicertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats permanents JPI" },
		{ "jpicertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l'aide des certificats de la zone de stockage des certificats permanents JPI" },
		{ "jpicertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats permanents JPI" },
{ "jpicertstore.cert.getkeystore", "Obtenir l'objet de stockage cl\u00e9 de la zone de stockage des certificats JPI" },
		
		{ "jpihttpscertstore.cert.loading", "Chargement des certificats Https JPI depuis {0}" },
		{ "jpihttpscertstore.cert.loaded", "Certificats Https JPI charg\u00e9s depuis {0}" },
		{ "jpihttpscertstore.cert.saving", "Enregistrement des certificats Https JPI dans {0}" },
		{ "jpihttpscertstore.cert.saved", "Certificats Https JPI enregistr\u00e9s dans {0}" },
		{ "jpihttpscertstore.cert.adding", "Ajout du certificat Https dans la zone de stockage des certificats permanents JPI", },
		{ "jpihttpscertstore.cert.added", "Certificat Https ajout\u00e9 comme alias {0} dans la zone de stockage des certificats permanents JPI " },
		{ "jpihttpscertstore.cert.removing", "Suppression du certificat Https dans la zone de stockage des certificats permanents JPI" },
		{ "jpihttpscertstore.cert.removed", "Certificat Https supprim\u00e9 comme alias {0} dans la zone de stockage des certificats permanents JPI " }, 
		{ "jpihttpscertstore.cert.instore", "Recherche du certificat Https dans la zone de stockage des certificats permanents JPI" },
		{ "jpihttpscertstore.cert.canverify", "D\u00e9terminer si le certificat Https peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l'aide des certificats de la zone de stockage des certificats permanents JPI" },
		{ "jpihttpscertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat Https dans la zone de stockage des certificats permanents JPI" },
{ "jpihttpscertstore.cert.getkeystore", "Obtenir l'objet de stockage cl\u00e9 de la zone de stockage des certificats Https" },

		{ "rootcertstore.cert.loading", "Chargement des certificats CA root depuis {0}" },
		{ "rootcertstore.cert.loaded", "Certificats CA root charg\u00e9s depuis {0}" },
		{ "rootcertstore.cert.noload", "Fichier de certificats CA root introuvable : {0}" },
		{ "rootcertstore.cert.saving", "Enregistrement des certificats CA root dans {0}" },
		{ "rootcertstore.cert.saved", "Certificats CA root enregistr\u00e9s dans {0}" },
		{ "rootcertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats CA root", },
		{ "rootcertstore.cert.added", "Certificat ajout\u00e9 comme alias {0} dans la zone de stockage des certificats CA root " },
		{ "rootcertstore.cert.removing", "Suppression du certificat de la zone de stockage des certificats CA root" },
		{ "rootcertstore.cert.removed", "Certificat supprim\u00e9 comme alias {0} dans la zone de stockage des certificats CA root " },
		{ "rootcertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats CA root" },
		{ "rootcertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l'aide des certificats de la zone de stockage des certificats CA root" },
		{ "rootcertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats CA root" },
{ "rootcertstore.cert.getkeystore", "Obtenir l'objet de stockage cl\u00e9 de la zone de stockage des certificats CA root" },
{ "roothttpscertstore.cert.getkeystore", "Obtenir l'objet de stockage cl\u00e9 de la zone de stockage des certificats CA root Https" },
		{ "rootcertstore.cert.verify.ok", "La v\u00e9rification du certificat \u00e0 l'aide des certificats CA root a r\u00e9ussi" },
		{ "rootcertstore.cert.verify.fail", "La v\u00e9rification du certificat \u00e0 l'aide des certificats CA root a \u00e9chou\u00e9" },
	{ "rootcertstore.cert.tobeverified", "Certificat \u00e0 verifier :\n{0}" },
	{ "rootcertstore.cert.tobecompared", "Comparaison entre le certificat et le certificat CA root :\n{0}" },

		{ "roothttpscertstore.cert.loading", "Chargement des certificats Https CA root depuis {0}" },
		{ "roothttpscertstore.cert.loaded", "Certificats Https CA root charg\u00e9s depuis {0}" },
		{ "roothttpscertstore.cert.noload", "Fichier de certificats Https CA root introuvable: " },
		{ "roothttpscertstore.cert.saving", "Enregistrement des certificats Https CA root dans {0}" },
		{ "roothttpscertstore.cert.saved", "Certificats Https CA root enregistr\u00e9s dans " },
		{ "roothttpscertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats Https CA root", },
		{ "roothttpscertstore.cert.added", "Certificat ajout\u00e9 comme alias dans la zone de stockage des certificats Https CA root " },
		{ "roothttpscertstore.cert.removing", "Suppression du certificat de la zone de stockage des certificats Https CA root" },
		{ "roothttpscertstore.cert.removed", "Certificat supprim\u00e9 comme alias dans la zone de stockage des certificats Https CA root " }, 
		{ "roothttpscertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats Https CA root" },
		{ "roothttpscertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l'aide des certificats de la zone de stockage des certificats Https CA root" },
		{ "roothttpscertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats Https CA root" },
		{ "roothttpscertstore.cert.verify.ok", "La v\u00e9rification du certificat \u00e0 l'aide des certificats Https CA root a r\u00e9ussi" },
		{ "roothttpscertstore.cert.verify.fail", "La v\u00e9rification du certificat \u00e0 l'aide des certificats Https CA root a \u00e9chou\u00e9" },
	{ "roothttpscertstore.cert.tobeverified", "Certificat \u00e0 verifier :\n{0}" },
	{ "roothttpscertstore.cert.tobecompared", "Comparaison entre le certificat et le certificat Https CA root :\n{0}" },

		{ "sessioncertstore.cert.loading", "Chargement des certificats depuis la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.loaded", "Certificats charg\u00e9s depuis la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.saving", "Enregistrement des certificats dans la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.saved", "Certificats enregistr\u00e9s dans la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats de session JPI", },
		{ "sessioncertstore.cert.added", "Certificat ajout\u00e9 dans la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.removing", "Suppression du certificat de la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.removed", "Certificat supprim\u00e9 de la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l'aide des certificats de la zone de stockage des certificats de session JPI" },
		{ "sessioncertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats de session JPI" },
{ "sessioncertstore.cert.getkeystore", "Obtenir l'objet de stockage cl\u00e9 de la zone de stockage des certificats de session JPI" },
		{ "hostnameverifier.automation.ignoremismatch", "Automatisation : Ignorer la non-concordance de nom d'h\u00f4te" },
        { "pluginclassloader.created_files", "{0} a \u00e9t\u00e9 cr\u00e9\u00e9 dans le cache." },
		    { "pluginclassloader.deleting_files", "Suppression des fichiers JAR du cache." },
		    { "pluginclassloader.file", "   suppression du cache {0}" },
		    { "pluginclassloader.empty_file", "{0} est vide, suppression du cache." },
		    
		 { "trustdecider.check.basicconstraints", "La v\u00e9rification des contraintes de base dans le certificat a \u00e9chou\u00e9" },
		 { "trustdecider.check.leafkeyusage", "La v\u00e9rification de la syntaxe de la cl\u00e9 du noeud terminal dans le certificat a \u00e9chou\u00e9"},
		{ "trustdecider.check.signerkeyusage", "La v\u00e9rification de la syntaxe de la cl\u00e9 du signataire dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.extensions", "La v\u00e9rification des extensions critiques dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.signature", "La v\u00e9rification de la signature dans le certificat a \u00e9chou\u00e9" }, 
		{ "trustdecider.check.basicconstraints.certtypebit", "La v\u00e9rification du bit du type de netscape dans le certificat a \u00e9chou\u00e9" }, 
		{ "trustdecider.check.basicconstraints.extensionvalue", "La v\u00e9rification de la valeur de l'extension de netscape dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.basicconstraints.bitvalue", "La v\u00e9rification des bits 5, 6 et 7 de netscape dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.basicconstraints.enduser", "La v\u00e9rification des actions de l'utilisateur final en tant que CA dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.basicconstraints.pathlength", "La v\u00e9rification des contraintes li\u00e9es \u00e0 la longueur du chemin d'acc\u00e8s dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.leafkeyusage.length", "La v\u00e9rification de la longueur de la syntaxe de la cl\u00e9 dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.leafkeyusage.digitalsignature", "La v\u00e9rification de la signature num\u00e9rique dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.leafkeyusage.extkeyusageinfo", "La v\u00e9rification des informations relatives \u00e0 la syntaxe de la cl\u00e9 d'extension dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.leafkeyusage.certtypebit", "La v\u00e9rification du bit du type de netscape dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.signerkeyusage.lengthandbit", "La v\u00e9rification de la longueur et du bit dans le certificat a \u00e9chou\u00e9" },
		{ "trustdecider.check.signerkeyusage.keyusage", "La v\u00e9rification de la syntaxe de la cl\u00e9 dans le certificat a \u00e9chou\u00e9" },
{ "trustdecider.check.canonicalize.updatecert", "Mettre \u00e0 jour le certificat root \u00e0 l'aide du certificat du fichier cacerts" },
{ "trustdecider.check.canonicalize.missing", "Ajouter le certificat root manquant" },
{ "trustdecider.check.gettrustedcert.find", "Rechercher le CA root valide dans le fichier cacerts" },
{ "trustdecider.check.gettrustedissuercert.find", "Rechercher le CA root valide absent du fichier cacerts" },		
		{ "trustdecider.user.grant.session", "L'utilisateur a accord\u00e9 les droits d'acc\u00e8s au code pour cette session seulement" },
		{ "trustdecider.user.grant.forever", "L'utilisateur a accord\u00e9 les droits d'acc\u00e8s au code pour toujours" },
		{ "trustdecider.user.deny", "L'utilisateur a refus\u00e9 les droits d'acc\u00e8s au code" },
		{ "trustdecider.automation.trustcert", "Automatisation : Autoriser le certificat RSA pour la signature" },
		{ "x509trustmgr.automation.ignoreclientcert", "Automatisation : Ignorer le certificat de client non autoris\u00e9" },
		{ "x509trustmgr.automation.ignoreservercert", "Automatisation : Ignorer le certificat de serveur non autoris\u00e9" },

		{ "appletcontext.audio.loaded", "Clip audio charg\u00e9 : {0}" },
		{ "appletcontext.image.loaded", "Image charg\u00e9e : {0}" },

		{ "securitymgr.automation.printing", "Automatisation : Accepter l'impression" },

		{ "classloaderinfo.referencing", "R\u00e9f\u00e9rence au chargeur de classes : {0}, refcount={1}" },
		{ "classloaderinfo.releasing", "Lib\u00e9ration du chargeur de classes : {0}, refcount={1}" },
		{ "classloaderinfo.caching", "Mise en cache du chargeur de classes : {0}" },
		{ "classloaderinfo.cachesize", "Taille de cache du chargeur de classes courant : {0}" },
		{ "classloaderinfo.num", "Nombre de chargeurs de classes mis en cache sur {0}, unreference {1}" },

		{ "trace.listener.added", "R\u00e9cepteur de tra\u00e7age ajout\u00e9 :{0} " },
		{ "trace.listener.removed", "R\u00e9cepteur de tra\u00e7age supprim\u00e9 : {0}" },

		{ "cookiehandler.cache", "Cache de cookies : " },
		{ "cookiehandler.server", "Serveur {0} demandant de d\u00e9finir un cookie avec \"{1}\"" },
		{ "cookiehandler.connect", "Connexion {0} avec cookie \"{1}\"" },	
		{ "cookiehandler.ignore.setcookie", "Impossible de traiter les cookies - ignorer la fonction de \"d\u00e9finition d'un cookie\"" },
		{ "cookiehandler.noservice", "Impossible de traiter les cookies - utilisez le cache pour d\u00e9terminer le \"cookie\"" },

		{ "jsobject.eval", "Evaluer {0} = {1}" },
		   { "jsobject.call", "JSObject::call: name={0}, url={1}, permission={2}" },
	           { "jsobject.eval.url.permission", "JSObject::eval({0}), url={1}, permission={2}" },
        	   { "jsobject.getMember", "JSObject::getMember: name={0}, url={1}, permission={2}" },
                   { "jsobject.setMember", "JSObject::setMember: name={0}, url={1}, permission={2}" },
                   { "jsobject.removeMember", "JSObject::removeMember: name={0}, url={1}, permission={2}" },
                   { "jsobject.getSlot", "JSObject::getSlot: {0}, url={1}, permission={2}" },
                   { "jsobject.setSlot", "JSObject::setSlot: slot={0}, url={1}, permission={2}" },

		{ "applet_install.ok", "L'installation de l'applet est termin\u00e9e." },
		{ "applet_install.fail", "L'installation de l'applet a \u00e9chou\u00e9." },

		{ "optpkg.install.info", "Installation du module optionnel {0}" },
		{ "optpkg.install.fail", "L'installation du module optionnel a \u00e9chou\u00e9." },
		{ "optpkg.install.ok", "L'installation du module optionnel a r\u00e9ussi." },
		{ "optpkg.install.automation", "Automatisation : Accepter l'installation de modules Java optionnels" },
		{ "optpkg.install.granted", "T\u00e9l\u00e9chargement du module optionnel autoris\u00e9 par l''utilisateur, t\u00e9l\u00e9charger \u00e0 partir de {0}" },
		{ "optpkg.install.deny", "T\u00e9l\u00e9chargement du module optionnel non autoris\u00e9 par l'utilisateur" },
		{ "optpkg.install.begin", "Installation {0}" },
		{ "optpkg.install.java.launch", "D\u00e9marrage du programme d'installation Java" },
		{ "optpkg.install.java.launch.command", "D\u00e9marrage du programme d''installation Java par {0}" },
		{ "optpkg.install.native.launch", "D\u00e9marrage du programme d'installation natif" },
		{ "optpkg.install.native.launch.fail.0", "Impossible d''ex\u00e9cuter {0}" },
		{ "optpkg.install.native.launch.fail.1", "L''acc\u00e8s \u00e0 {0} a \u00e9chou\u00e9" },
		{ "optpkg.install.raw.launch", "Installation du module optionnel brut" },
		{ "optpkg.install.raw.copy", "Copie du module optionnel brut \u00e0 partir de {0} vers {1}" },
		{ "optpkg.install.error.nomethod", "Fournisseur d'extension d\u00e9pendant non install\u00e9 : Impossible d'obtenir la m\u00e9thode "
		  	                     + " addExtensionInstallationProvider" },
		{ "optpkg.install.error.noclass", "Fournisseur d'extension d\u00e9pendant non install\u00e9 : Impossible d'obtenir la classe "
		                     + "sun.misc.ExtensionDependency" },

		{ "dialogfactory.user.selected", "Utilisateur s\u00e9lectionn\u00e9 : {0}" },
		{ "dialogfactory.user.typed", "Utilisateur indiqu\u00e9 : {0}" },

		{"progress_dialog.downloading", "Plug-in : T\u00e9l\u00e9chargement..."},
        {"progress_dialog.dismiss_button", "Abandonner"},
        {"progress_dialog.dismiss_button.acceleratorKey", new Integer(KeyEvent.VK_A)},
        {"progress_dialog.from", "\u00e0 partir de"},                

        {"applet_viewer.color_tag", "Nombre de composants incorrect dans {0}"},
                
        {"progress_info.downloading", "T\u00e9l\u00e9chargement de fichiers JAR"},
        {"progress_bar.preload", "Pr\u00e9-chargement des fichiers JAR : {0}"},
        
        {"cache.size", "Taille du cache : {0}"},
        {"cache.cleanup", "La taille du cache est : {0} octets. Vous devez lib\u00e9rer de l''espace"},
        {"cache.full", "Le cache est plein : suppression du fichier {0}"},
        {"cache.inuse", "Impossible de supprimer le fichier {0} parce qu''il est utilis\u00e9 par cette application"},
        {"cache.notdeleted", "Impossible de supprimer le fichier {0} car il peut \u00eatre en cours d''utilisation par cette et/ou une autre application"},
        {"cache.out_of_date", "La copie du cache de {0} n''est pas actualis\u00e9e\n  Copie du cache : {1}\n  Copie Serveur : {2}"},
        {"cache.loading", "Chargement de {0} \u00e0 partir du cache"},
        {"cache.cache_warning", "ATTENTION : Impossible de mettre {0} en cache"},
        {"cache.downloading", "T\u00e9l\u00e9chargement de {0} dans le cache"},
        {"cache.cached_name", "Nom du fichier mis en cache : {0}"},
        {"cache.load_warning", "ATTENTION : erreur de lecture de {0} \u00e0 partir du cache."},
        {"cache.disabled", "Le cache est d\u00e9sactiv\u00e9 par l'utilisateur"},
        {"cache.minSize", "Le cache est d\u00e9sactiv\u00e9, la limite du cache est d\u00e9finie \u00e0 {0}, au moins 5 Mo doivent \u00eatre sp\u00e9cifi\u00e9s"},
        {"cache.directory_warning", "ATTENTION : {0} n''est pas un r\u00e9pertoire. La fonction de cache sera d\u00e9sactiv\u00e9e."},
       	{"cache.response_warning", "ATTENTION : R\u00e9ponse inattendue {0} pour {1}.  Le fichier sera de nouveau t\u00e9l\u00e9charg\u00e9."},
        {"cache.enabled", "Le cache est activ\u00e9"},
        {"cache.location", "Emplacement : {0}"},
        {"cache.maxSize", "Taille maximale : {0}"},
        {"cache.create_warning", "ATTENTION : Impossible de cr\u00e9er le r\u00e9pertoire du cache {0}.  La mise en cache sera d\u00e9sactiv\u00e9e."},
        {"cache.read_warning", "ATTENTION : Impossible de lire le r\u00e9pertoire du cache {0}.  La mise en cache sera d\u00e9sactiv\u00e9e."},
        {"cache.write_warning", "ATTENTION : Impossible d''\u00e9crire dans le r\u00e9pertoire du cache {0}.  La mise en cache sera d\u00e9sactiv\u00e9e."},
        {"cache.compression", "Niveau de compression : {0}"},
        {"cache.cert_load", "Les certificats pour {0} sont lus \u00e0 partir du cache JAR"},
	{"cache.jarjar.invalid_file", "Le fichier .jarjar contient un fichier qui n'est pas au format .jar"},
	{"cache.jarjar.multiple_jar", "Le fichier .jarjar contient plusieurs fichiers au format .jar"},
        {"cache.version_checking", "V\u00e9rification de version pour {0}. La version sp\u00e9cifi\u00e9e est {1}"},
        {"cache.preloading", "Pr\u00e9-chargement du fichier {0}"},

	{ "cache_viewer.caption", "D\u00e9tails - Cache" },
	{ "cache_viewer.refresh", "Actualiser" },
	{ "cache_viewer.refresh.acceleratorKey", new Integer(KeyEvent.VK_A) },
	{ "cache_viewer.remove", "Supprimer" },
	{ "cache_viewer.remove.acceleratorKey", new Integer(KeyEvent.VK_S) },
	{ "cache_viewer.close", "Fermer" },
	{ "cache_viewer.close.acceleratorKey", new Integer(KeyEvent.VK_F) },
	{ "cache_viewer.name", "Nom" },
	{ "cache_viewer.type", "Type" },
	{ "cache_viewer.size", "Taille" },
	{ "cache_viewer.modify_date", "Derni\u00e8re modification" },
	{ "cache_viewer.expiry_date", "Date d'expiration" },
	{ "cache_viewer.url", "URL" },
	{ "cache_viewer.version", "Version" },
	{ "cache_viewer.help.name", "Nom du fichier mis en cache" },
	{ "cache_viewer.help.type", "Type du fichier mis en cache" },
	{ "cache_viewer.help.size", "Taille du fichier mis en cache" },
	{ "cache_viewer.help.modify_date", "Derni\u00e8re modification du fichier mis en cache" },
	{ "cache_viewer.help.expiry_date", "Date d'expiration du fichier mis en cache" },
	{ "cache_viewer.help.url", "URL de t\u00e9l\u00e9chargement du fichier mis en cache" },
	{ "cache_viewer.help.version", "Version du fichier mis en cache" },
	{ "cache_viewer.delete.text", "<html><b>Fichier non supprim\u00e9</b></html>{0} est peut-\u00eatre en cours d''utilisation.\n" },
	{ "cache_viewer.delete.caption", "Erreur - Cache" },
	{ "cache_viewer.type.zip", "Jar" },
	{ "cache_viewer.type.class", "Classe" },
	{ "cache_viewer.type.wav", "Son Wav" },
	{ "cache_viewer.type.au", "Son Au" },
	{ "cache_viewer.type.gif", "Image Gif" },
	{ "cache_viewer.type.jpg", "Image Jpeg" },

	{ "net.proxy.loading.ie", "Chargement de la configuration du proxy \u00e0 partir d'Internet Explorer ..."},
	{ "net.proxy.loading.ns", "Chargement de la configuration du proxy \u00e0 partir de Netscape Navigator ..."},
	{ "net.proxy.loading.userdef", "Chargement de la configuration du proxy d\u00e9finie par l'utilisateur ..."},
	{ "net.proxy.loading.direct", "Chargement de la configuration directe du proxy ..."},
	{ "net.proxy.loading.manual", "Chargement de la configuration manuelle du proxy ..."},
	{ "net.proxy.loading.auto",   "Chargement de la configuration auto du proxy ..."},
	{ "net.proxy.loading.browser",   "Chargement de la configuration du proxy du navigateur ..."},
	{ "net.proxy.loading.manual.error", "Impossible d'utiliser la configuration du proxy manuelle - repli sur DIRECTE"},
	{ "net.proxy.loading.auto.error", "Impossible d'utiliser la configuration du proxy auto - repli sur MANUELLE"},
	{ "net.proxy.loading.done", "Termin\u00e9."},
	{ "net.proxy.browser.pref.read", "Lecture du fichier de pr\u00e9f\u00e9rences utilisateur \u00e0 partir de {0}"},
	{ "net.proxy.browser.proxyEnable", "    Activation proxy : {0}"},
	{ "net.proxy.browser.proxyList",     "    Liste proxy : {0}"},
	{ "net.proxy.browser.proxyOverride", "    Priorit\u00e9 proxy : {0}"},
	{ "net.proxy.browser.autoConfigURL", "    URL config. auto : {0}"},
	{ "net.proxy.browser.smartConfig", "Ex\u00e9cutez une commande Ping sur le serveur proxy {0} sur le port {1}"},
        { "net.proxy.browser.connectionException", "Le serveur proxy {0} sur le port {1} est inaccessible "},
	{ "net.proxy.ns6.regs.exception", "Erreur lors de la lecture du fichier du registre : {0}"},
	{ "net.proxy.pattern.convert", "Convertir la liste de contournement de proxy en expression r\u00e9guli\u00e8re : "},
	{ "net.proxy.pattern.convert.error", "Impossible de convertir la liste de contournement de proxy en expression r\u00e9guli\u00e8re - ignorer"},
	{ "net.proxy.auto.download.ins", "T\u00e9l\u00e9chargement du fichier INS \u00e0 partir de {0}" },
	{ "net.proxy.auto.download.js", "T\u00e9l\u00e9chargement du fichier de proxy auto \u00e0 partir de {0}" },
	{ "net.proxy.auto.result.error", "Impossible de d\u00e9terminer le r\u00e9glage proxy de l'\u00e9valuation - repli sur DIRECTE"},
        { "net.proxy.service.not_available", "Service de proxy non disponible pour {0} - configuration DIRECT d\u00e9finie par d\u00e9faut" },

	{ "lifecycle.applet.found", "Le pr\u00e9c\u00e9dent applet interrompu a \u00e9t\u00e9 trouv\u00e9 dans le cache de cycle de vie" },
	{ "lifecycle.applet.support", "L'applet prend en charge les mod\u00e8les de cycle de vie h\u00e9rit\u00e9s - ajout de l'applet au cache de cycle de vie" },
	{ "lifecycle.applet.cachefull", "Le cache de cycle de vie est plein - veuillez supprimer au moins les applets utilis\u00e9s r\u00e9cemment" },

	{ "com.method.ambiguous", "Impossible de s\u00e9lectionner une m\u00e9thode, param\u00e8tres ambigus" },
	{ "com.method.notexists", "{0} : cette m\u00e9thode n''existe pas" },
	{ "com.notexists", "{0} : cette m\u00e9thode/propri\u00e9t\u00e9  n''existe pas" },
	{ "com.method.invoke", "Appel de la m\u00e9thode : {0}" },
	{ "com.method.jsinvoke", "Appel de la m\u00e9thode JS : {0}" },
	{ "com.method.argsTypeInvalid", "Les param\u00e8tres ne peuvent pas \u00eatre convertis selon les types requis" },
	{ "com.method.argCountInvalid", "Le nombre d'arguments est incorrect" },
	{ "com.field.needsConversion", "Conversion requise : {0} --> {1}" },
	{ "com.field.typeInvalid", " impossible de convertir selon le type : {0}" },
	{ "com.field.get", "R\u00e9cup\u00e9ration de la propri\u00e9t\u00e9 : {0}" },
	{ "com.field.set", "D\u00e9finition de la propri\u00e9t\u00e9 : {0}" },

	{"about.java.version", "                 Version"},
	{"about.prompt.info", "Pour de plus amples informations, consultez le site"},
	{"about.home.link", "http://www.java.com"},
	{"about.option.close", "Fermer"},
	{"about.option.close.acceleratorKey", new Integer(KeyEvent.VK_F) },
	{"about.legal.note", "Copyright 2003 Sun Microsystems, Inc. Tous droits r\u00e9serv\u00e9s. L'utilisation " +
			     "est soumise \u00e0 des conditions de licence. Le logiciel d\u00e9tenu par des tiers, " +
			     "et qui comprend la technologie relative aux polices de caract\u00e8res, est prot\u00e9g\u00e9 " +
			     "par un copyright et licenci\u00e9 par des fournisseurs de Sun. Copyright partiel " +
			     "Eastman Kodak Company 1992. Ce produit inclut le code licenci\u00e9 par RSA Data " +
			     "Security. Sun, Sun Microsystems, le logo Sun, Java, Solaris et J2SE sont des " +
			     "marques de fabrique ou des marques d\u00e9pos\u00e9es de Sun Microsystems, Inc. aux " +
			     "\u00c9tats-Unis et dans d'autres pays. Toutes les marques SPARC sont utilis\u00e9es " +
			     "sous licence et sont des marques de fabrique ou des marques d\u00e9pos\u00e9es de " +
			     "SPARC International, Inc. aux \u00c9tats-Unis et dans d'autres pays. " +
			     "Acquisitions f\u00e9d\u00e9rales: Logiciel commercial - utilisateurs gouvernementaux " +
			     "soumis aux conditions g\u00e9n\u00e9rales de licence standard."}
    
    };
}

