/*
 * @(#)Activator_sv.java	1.40 03/05/11
 *
 * Copyright 2003 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package sun.plugin.resources;

import java.util.ListResourceBundle;
import java.awt.event.KeyEvent;
/**
 * Swedish version of Activator strings.
 *
 * @author Jerome Dochez
 */

public class Activator_sv extends ListResourceBundle {

    public Object[][] getContents() {
        return contents;
    }

    static final Object[][] contents = {
	{ "panel.caption", "Kontrollpanelen f\u00f6r Java Plug-in" }, 
        { "product_name", "Java(TM) Plug-in" },
        { "version", "Version" },
        { "default_vm_version", "Standardversion f\u00f6r virtuell maskin " },
        { "using_jre_version", "Anv\u00e4nder JRE-version" },
        { "user_home_dir", "Anv\u00e4ndarens hemkatalog" },
        { "user_overriden_browser", "Anv\u00e4ndaren har \u00e5sidosatt webbl\u00e4sarens proxyinst\u00e4llningar." },
        { "proxy_configuration", "Proxy-konfiguration: " },
        { "browser_config", "Proxykonfiguration f\u00f6r webbl\u00e4sare" },
        { "auto_config", "Automatisk proxy-konfiguration" },
        { "manual_config", "Manuell konfiguration" },
        { "no_proxy", "Ingen proxy" },
        { "proxy_is", "Proxy: " },
        { "proxy_override_is", "Proxy-ers\u00e4ttningar:" },
        { "loading", "L\u00e4ser in {0}...." },
        { "java_applet", "Java-applet" },
        { "failed", "Inl\u00e4sningen av Java-applet misslyckades..." },
        { "image_failed", "Kunde inte skapa anv\u00e4ndardefinierad bild.  Kontrollera bildfilens namn." },
        { "java_bean", "JavaBeans" },
        { "java_not_enabled", "Java har inte aktiverats" },
        { "exception", "Undantag: {0}" },

        { "net.connect.no_proxy", "Ansluter {0} utan proxy " },
	{ "net.connect.proxy_is", "Ansluter {0} med proxy={1}" },

        { "bean_code_and_ser", "B\u00f6na kan inte ha b\u00e5de CODE och JAVA_OBJECT definierade " },
        { "status_applet", "Applet {0} {1}" },

        // Resources associated with SecurityManager print Dialog:
	{ "print.caption", "Beh\u00f6ver bekr\u00e4ftelse - skriv ut" },
        { "print.message", new String[]{
		"<html><b>F\u00f6rfr\u00e5gan om utskrivning</b></html>Applet vill skriva ut. Vill du forts\u00e4tta?\n"}},
	{ "print.checkBox", "Visa inte den h\u00e4r dialogrutan igen" },
	{ "print.buttonYes", "Ja" },
	{ "print.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_J)},
	{ "print.buttonNo", "Nej" },
	{ "print.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},

	{ "https_dialog.caption", "Varning - HTTPS" },
	{ "https_dialog.text", "<html><b>V\u00e4rdnamn st\u00e4mmer ej \u00f6verens</b></html>V\u00e4rdnamnet i certifikatet f\u00f6r servers\u00e4kerhet st\u00e4mmer inte \u00f6verens med serverns namn." 
		+"\n\nV\u00e4rdnamn f\u00f6r webbadressen: {0}" 
		+"\nV\u00e4rdnamn fr\u00e5n certifikatet: {1}" 
		+"Vill du forts\u00e4tta?"},
	  { "https_dialog.unknown.host", "Ok\u00e4nd v\u00e4rddator"},

	{ "security_dialog.caption", "Varning - S\u00e4kerhet" },
        { "security_dialog.text0", "Vill du installera och k\u00f6ra signerad applet distribuerat av \"{0}\"?"
        +"\n\nUtgivaren har godk\u00e4nts av: \"{1}\"" },
        { "security_dialog_https.text0", "Accepterar du certifikatet fr\u00e5n webbadressen \"{0}\" i syfte att utbyta krypterad information?" 
        +"\n\nUtgivaren har godk\u00e4nts av: \"{1}\"" },
        { "security_dialog.text1", "Varning: \"{0}\" f\u00f6rs\u00e4krar att inneh\u00e5llet \u00e4r s\u00e4kert. Du b\u00f6r endast installera/visa inneh\u00e5llet om du litar p\u00e5 att \"{0}\" g\u00f6r denna f\u00f6rs\u00e4kran.\n\n"}, 
	  {"security_dialog.unknown.issuer", "Ok\u00e4nd utf\u00e4rdare"},
	  {"security_dialog.unknown.subject", "Ok\u00e4nt f\u00f6rem\u00e5l"},
	{ "security_dialog.certShowName", "{0}({1})" },
    	  { "security_dialog.rootCANotValid", "S\u00e4kerhetscertifikatet har utf\u00e4rdats av ett f\u00f6retag som inte \u00e4r s\u00e4kert." },
    	  { "security_dialog.rootCAValid", "S\u00e4kerhetscertifikatet har utf\u00e4rdats av ett f\u00f6retag som \u00e4r s\u00e4kert." },
    	  { "security_dialog.timeNotValid", "S\u00e4kerhetscertifikatet har f\u00f6rfallit eller har \u00e4nnu inte b\u00f6rjat g\u00e4lla." },
    	  { "security_dialog.timeValid", "S\u00e4kerhetscertifikatet har inte f\u00f6rfallit och \u00e4r fortfarande giltigt." },
	{ "security_dialog.buttonAlways", "Alltid" },
        { "security_dialog.buttonAlways.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "security_dialog.buttonYes", "Ja" },
	{ "security_dialog.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_J)},
        { "security_dialog.buttonNo", "Nej" },
	{ "security_dialog.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "security_dialog.buttonViewCert", "Fler detaljer" },	
        { "security_dialog.buttonViewCert.acceleratorKey", new Integer(KeyEvent.VK_F)},
        
	{ "cert_dialog.caption", "Detaljer-Vertifikat" },
	{ "cert_dialog.certpath", "Certifikatv\u00e4g" },
        { "cert_dialog.field.Version", "Version" },
        { "cert_dialog.field.SerialNumber", "Serienummer" },
        { "cert_dialog.field.SignatureAlg", "Signaturalgoritm" },
        { "cert_dialog.field.Issuer", "Utf\u00e4rdare" },
        { "cert_dialog.field.EffectiveDate", "G\u00e4llande datum" },
        { "cert_dialog.field.ExpirationDate", "Utg\u00e5ngsdatum" },
        { "cert_dialog.field.Validity", "Giltighet" },
        { "cert_dialog.field.Subject", "\u00c4mne" },
        { "cert_dialog.field.Signature", "Signatur" },
        { "cert_dialog.field", "F\u00e4lt" },
        { "cert_dialog.value", "V\u00e4rde" },

        { "cert_dialog.close", "St\u00e4ng" },
	{ "cert_dialog.close.acceleratorKey", new Integer(KeyEvent.VK_S) },

	{ "net.authenticate.caption", "L\u00f6senord kr\u00e4vs- Networking"},
	{ "net.authenticate.label", "<html><b>Skriv in ditt anv\u00e4ndarnamn och l\u00f6senord:</b></html>"},
        { "net.authenticate.resource", "Resurs:" },
        { "net.authenticate.username", "Anv\u00e4ndarnamn:" },
        { "net.authenticate.password", "L\u00f6senord:" },
        { "net.authenticate.firewall", "Brandv\u00e4gg:" },
        { "net.authenticate.realm", "Omr\u00e5de:" },
        { "net.authenticate.scheme", "Schema:" },
	  { "net.authenticate.unknownSite", "Ok\u00e4nd plats" },

        { "console.caption", "Java systemf\u00f6nster" },
        { "console.clear", "T\u00f6m" },
        { "console.clear.acceleratorKey", new Integer(KeyEvent.VK_T)},
        { "console.close", "St\u00e4ng" },
        { "console.close.acceleratorKey", new Integer(KeyEvent.VK_S) },
        { "console.copy", "Kopiera" },
        { "console.copy.acceleratorKey", new Integer(KeyEvent.VK_K) },

	{ "optpkg.cert_expired", "<html><b>Utg\u00e5nget certifikat</b></html>Installation av valfritt paket avbryts.\n" },
	{ "optpkg.cert_notyieldvalid", "<html><b>Certifikatet \u00e4r ej giltigt</b></html>Installation av valfritt paket avbryts.\n" },
	{ "optpkg.cert_notverify", "<html><b>Ej verifierat certifikat</b></html>Installation av valfritt paket avbryts.\n" },
	{ "optpkg.general_error", "<html><b>Generellt undantag</b></html>Installation av valfritt paket avbryts.\n" },
	{ "optpkg.caption", "Varning - Valfritt paket" },
	{ "optpkg.installer.launch.wait", "<html><b>Installerar valfritt paket</b></html>Klick OK f\u00f6r att forts\u00e4tta laddning av applet efter avslutad installation av valfritt paket.\n" },
	{ "optpkg.installer.launch.caption", "Installation p\u00e5g\u00e5r - Valfritt paket"},
	{ "optpkg.prompt_user.new_spec.text", "<html><b>F\u00f6rfr\u00e5gan om nerladdning</b></html>Applet beh\u00f6ver en nyare version (specifikation {0}) av valfritt paket \"{1}\" fr\u00e5n {2}\n\nVill du forts\u00e4tta?" },
	{ "optpkg.prompt_user.new_impl.text", "<html><b>F\u00f6rfr\u00e5gan om nerladdning</b></html>Applet beh\u00f6ver en nyare version (implementering {0}) av valfritt paket \"{1}\" fr\u00e5n {2}\n\nVill du forts\u00e4tta?" },
	{ "optpkg.prompt_user.new_vendor.text", "<html><b>F\u00f6rfr\u00e5gan om nerladdning</b></html>Applet kr\u00e4ver ({0}) av valfritt paket \"{1}\" {2} fr\u00e5n {3}\n\nVill fu forts\u00e4tta?" },
	{ "optpkg.prompt_user.default.text", "<html><b>F\u00f6rfr\u00e5gan om nerladdning</b></html>Applet kr\u00e4ver installation av valfritt paket \"{0}\" fr\u00e5n {1}\n\nVill du forts\u00e4tta?" },

	{ "rsa.cert_expired", "<html><b>Utg\u00e5nget certifikat</b></html>Kod kommer att behandlas som osignerad.\n" },
	{ "rsa.cert_notyieldvalid", "<html><b>Ej giltigt certifikat</b></html>Kod kommer att behandlas som osignerad.\n" },
	{ "rsa.general_error", "<html><b>Ej verifierat certifikat</b></html>Kod kommer att behandlas som osignerad.\n" },

	{ "usability.confirmDialogTitle", "Bekr\u00e4ftelse kr\u00e4vs - Java" },
	{ "usability.inputDialogTitle", "Information kr\u00e4vs - Java" },
	{ "usability.messageDialogTitle", "Meddelande - Java" },
	{ "usability.exceptionDialogTitle", "Fel - Java" },
	{ "usability.optionDialogTitle", "Option - Java" },
	{ "usability.aboutDialogTitle", "Om - Java" },
        { "usability.confirm.yes", "Ja" },
        { "usability.confirm.yes.acceleratorKey", new Integer(KeyEvent.VK_J)},
        { "usability.confirm.no", "Nej" },
        { "usability.confirm.no.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "usability.moreInfo", "Fler detaljer" },	
        { "usability.moreInfo.acceleratorKey", new Integer(KeyEvent.VK_F)},
        { "usability.lessInfo", "F\u00e4rre detaljer" },	
        { "usability.lessInfo.acceleratorKey", new Integer(KeyEvent.VK_R)},
	{ "usability.java.home.link", "http://www.java.com" },

	{ "usability.general_error", "<html><b>Generella undantag</b></html>" },
	{ "usability.net_error", "<html><b>N\u00e4tverksundantag</b></html>" },
	{ "usability.security_error", "<html><b>S\u00e4kerhetsundanag</b></html>" },
	{ "usability.ext_error", "<html><b>Valfritt paket-undantag</b></html>" },

        { "usability.menu.show_console", "Visa systemf\u00f6nstret f\u00f6r Java" },
        { "usability.menu.hide_console", "D\u00f6lj systemf\u00f6nstret f\u00f6r Java" },
        { "usability.menu.about", "Om Java Plug-in" },
        { "usability.menu.copy", "Kopiera" },
	{ "usability.menu.open_console", "\u00d6ppna Java-konsol" },
	{ "usability.menu.about_java", "Om Java(TM)" },

	{ "proxy.error_caption", "Fel - Proxy-konfiguration" },
	{ "proxy.prefsfile.nsreg_error", "<html><b>Kan inte \u00e5terfinna proxy-inst\u00e4llningar</b></html>G\u00e5r tillbaka till annan proxy-konfiguration.\n" },

	{ "cache.error.text", "<html><b>Cachar Fel</b></html>Kan inte spara eller uppdatera filer i cachen." },
	{ "cache.error.caption", "Fel - Cache" },
	{ "cache.version_format_error", "{0} \u00e4r inte i formen xxxx.xxxx.xxxx.xxxx d\u00e4r x \u00e4r ett hexadecimal tal" },
		{ "cache.version_attrib_error", "Antalet attribut som angetts i \'cache_archive\' \u00f6verensst\u00e4mmer inte med dem i \'cache_version\'" },
	{ "cache.header_fields_missing", "Uppgift om n\u00e4r filen \u00e4ndrades senast och/eller f\u00f6rfallodatum \u00e4r inte tillg\u00e4nglig.  Jar-filen kommer inte att lagras i cacheminnet."},

		{ "applet.progress.load", "Laddar applet..." },
		{ "applet.progress.init", "Initierar applet..." },
		{ "applet.progress.start", "Startar applet..." },
		{ "applet.progress.stop", "Stoppar applet..." },
		{ "applet.progress.destroy", "F\u00f6rst\u00f6r applet..." },
		{ "applet.progress.dispose", "Kasserar applet..." },
		{ "applet.progress.quit", "Avslutar applet..." },
		{ "applet.progress.stoploading", "Stoppade laddning..." },
		{ "applet.progress.interrupted", "Avbr\u00f6t tr\u00e5d..." },
		{ "applet.progress.joining", "Kopplar applet-tr\u00e5d..."},
		{ "applet.progress.joined", "Kopplade applet-tr\u00e5d..."},
		{ "applet.progress.loadImage", "Laddar bild " },
		{ "applet.progress.loadAudio", "Laddar ljud " },
		{ "applet.progress.findinfo.0", "S\u00f6ker efter information..." },
		{ "applet.progress.findinfo.1", "Klar..." },
		{ "applet.progress.timeout.wait", "V\u00e4ntar p\u00e5 tidsgr\u00e4ns..." },
		{ "applet.progress.timeout.jointing", "Utf\u00f6r en sammanslagning..."},
		{ "applet.progress.timeout.jointed", "Klar med sammanslagning..." },


		{ "console.menu.text.top", "----------------------------------------------------\n" },
		{ "console.menu.text.c", "c:   t\u00f6m systemf\u00f6nster\n" },
		{ "console.menu.text.f", "f:   slutf\u00f6r objekt i slutf\u00f6ringsk\u00f6\n" },
		{ "console.menu.text.g", "g:   skr\u00e4pinsamling\n" },
		{ "console.menu.text.h", "h:   visa det h\u00e4r hj\u00e4lpmeddelandet\n" },
		{ "console.menu.text.j", "j:   dumpa jcov data\n"},
		{ "console.menu.text.l", "l:   dumpa classloader-lista\n" },
		{ "console.menu.text.m", "m:   skriv ut minnesf\u00f6rbrukning\n" },
		{ "console.menu.text.o", "o:   logga utl\u00f6sare\n" },
		{ "console.menu.text.p", "p:   ladda proxykonfiguration p\u00e5 nytt\n" },
		{ "console.menu.text.q", "q:   d\u00f6lj systemf\u00f6nster\n" },
		{ "console.menu.text.r", "r:   ladda policykonfiguration p\u00e5 nytt\n" },
		{ "console.menu.text.s", "s:   dumpa systemegenskaper\n" },
		{ "console.menu.text.t", "t:   dumpa tr\u00e5dlista\n" },
	{ "console.menu.text.v", "v:   dumpa tr\u00e5dlistan\n" },
		{ "console.menu.text.x", "x:   t\u00f6m classloader-cachen\n" },
		{ "console.menu.text.0", "0-5: ange sp\u00e5rningsniv\u00e5n till <n>\n" },
		{ "console.menu.text.tail", "----------------------------------------------------\n" },
		{ "console.done", "Klar." },
		{ "console.trace.level.0", "Sp\u00e5rningsniv\u00e5n angiven till 0: ingen ... klar." },
		{ "console.trace.level.1", "Sp\u00e5rningsniv\u00e5n angiven till 1: basic ... klar." },
		{ "console.trace.level.2", "Sp\u00e5rningsniv\u00e5n angiven till 2: basic, net ... klar." },
		{ "console.trace.level.3", "Sp\u00e5rningsniv\u00e5n angiven till 3: basic, net, security ... klar." },
		{ "console.trace.level.4", "Sp\u00e5rningsniv\u00e5n angiven till 4: basic, net, security, ext ... klar." },
		{ "console.trace.level.5", "Sp\u00e5rningsniv\u00e5n angiven till 5: basic, net, security, ext, liveconnect ... klar." },
		{ "console.log", "Loggningen angiven till: " },
		{ "console.completed", " .... klar." },
		{ "console.dump.thread", "Dumpa tr\u00e5dlista ...\n" },
	{ "console.dump.stack", "Dumpa tr\u00e5dlistan ...\n" },
		{ "console.dump.properties", "Dumpa systemegenskaper ...\n" },
		{ "console.clear.classloader", "T\u00f6m classloader-cachen ... klar." },
		{ "console.reload.policy", "Ladda policykonfiguration p\u00e5 nytt" },
		{ "console.reload.proxy", "Ladda proxykonfiguration p\u00e5 nytt ..." },
		{ "console.gc", "Skr\u00e4pinsamling" },
		{ "console.finalize", "Slutf\u00f6r objekt i slutf\u00f6ringsk\u00f6 " },
		{ "console.memory", "Minne: {0}K	Ledigt: {1}K	({2}%)" },
            { "console.jcov.error", "Jcov-k\u00f6rningsfel: kontrollera om du angett r\u00e4tt jcov-alternativ\n"},
            { "console.jcov.info", "Jcov-data dumpades\n"},

		{ "modality.register", "Registrerad tillst\u00e5ndsavlyssnare" },
		{ "modality.unregister", "Oregistrerad tillst\u00e5ndsavlyssnare" },
		{ "modality.pushed", "Push-\u00e5tg\u00e4rd p\u00e5 tillst\u00e5nd" },
		{ "modality.popped", "Pop-\u00e5tg\u00e4rd p\u00e5 tillst\u00e5nd" },

	    { "progress.listener.added", "Lade till f\u00f6rloppsavlyssnare: {0}" },
	    { "progress.listener.removed", "Tog bort f\u00f6rloppsavlyssnare: {0}" },

	    { "liveconnect.UniversalBrowserRead.enabled", "JavaScript: UniversalBrowserRead aktiverad" },
	    { "liveconnect.java.system", "JavaScript: anropar Java-systemkod" },
	    { "liveconnect.same.origin", "JavaScript: anropare och mottagare har samma ursprung" },
	    { "liveconnect.default.policy", "JavaScript: standardinst\u00e4lld s\u00e4kerhetspolicy = {0}" },
	    { "liveconnect.UniversalJavaPermission.enabled", "JavaScript: UniversalJavaPermission aktiverad" },
	   	{ "liveconnect.wrong.securitymodel", "S\u00e4kerhetsmodell f\u00f6r Netscape kan inte l\u00e4ngre hanteras.\n"
		                     + "\u00d6verg\u00e5 till s\u00e4kerhetsmodellen f\u00f6r Java 2 i st\u00e4llet.\n" },

	    { "jpicertstore.cert.loading", "Laddar JPI-certifikat fr\u00e5n {0}" },
	    { "jpicertstore.cert.loaded", "Laddade JPI-certifikat fr\u00e5n {0}" },
	    { "jpicertstore.cert.saving", "Sparar JPI-certifikat i {0} " },
	    { "jpicertstore.cert.saved", "Sparade JPI-certifikat i {0}" },
	    { "jpicertstore.cert.adding", "L\u00e4gger till certifikat i JPI-permanent certifikatlager", },
	    { "jpicertstore.cert.added", "Lade till certifikat i JPI-permanent certifikatlager som alias {0}" },
	    { "jpicertstore.cert.removing", "Tar bort certifikat i JPI-permanent certifikatlager" },
	    { "jpicertstore.cert.removed", "Tog bort certifikat i JPI-permanent certifikatlager som alias {0}" },
	    { "jpicertstore.cert.instore", "Kontrollerar om certifikatet finns i JPI-permanent certifikatlager" },
	    { "jpicertstore.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i JPI-permanent certifikatlager" },
	    { "jpicertstore.cert.iterator", "H\u00e4mta certifikatupprepare i JPI-permanent certifikatlager" },
{ "jpicertstore.cert.getkeystore", "H\u00e4mta nyckelarkivobjekt fr\u00e5n JPI-certifikatlager" },

          { "jpihttpscertstore.cert.loading", "Laddar JPI Https-certifikat fr\u00e5n {0}"},
          { "jpihttpscertstore.cert.loaded", "Laddade JPI Https-certifikat fr\u00e5n {0}"},
          { "jpihttpscertstore.cert.saving", "Sparar JPI Https-certifikat i {0}"},
          { "jpihttpscertstore.cert.saved", "Sparade JPI Https-certifikat i {0}"},
          { "jpihttpscertstore.cert.adding", "L\u00e4gger till Https-certifikat i JPI-permanent certifikatlager"},
	  { "jpihttpscertstore.cert.added", "Lade till Https-certifikat i JPI-permanent certifikatlager som alias {0}" },
          { "jpihttpscertstore.cert.removing", "Tar bort Https-certifikat ut JPI-permanent certifikatlager"},
          { "jpihttpscertstore.cert.removed", "Tog bort Https-certifikat JPI-permanent certifikatlager som alias {0}"},
          { "jpihttpscertstore.cert.instore", "Kontrollerar om Https-certifikat finns i JPI-permanent certifikatlager"},
	  { "jpihttpscertstore.cert.canverify", "Kontrollera om Https-certifikat kan bekr\u00e4ftas med certifikat i JPI-permanent certifikatlager"},
          { "jpihttpscertstore.cert.iterator", "H\u00e4mta Https-certifikatupprepare i JPI-permanent certifikatlager"},
{ "jpihttpscertstore.cert.getkeystore", "H\u00e4mta nyckelarkivobjekt fr\u00e5n Https-certifikatlager"},
	    { "rootcertstore.cert.loading", "Laddar Root CA-certifikat fr\u00e5n {0}" },
	    { "rootcertstore.cert.loaded", "Laddade Root CA-certifikat fr\u00e5n {0}" },
	    { "rootcertstore.cert.noload", "Root CA-certifikatfil hittades inte: {0}"},
	    { "rootcertstore.cert.saving", "Sparar Root CA-certifikat i {0}" },
	    { "rootcertstore.cert.saved", "Sparade Root CA-certifikat i {0}" },
	    { "rootcertstore.cert.adding", "L\u00e4gger till certifikat i Root CA-certifikatlager" },
	    { "rootcertstore.cert.added", "Lade till certifikat i Root CA-certifikatlager som alias {0}" },
	    { "rootcertstore.cert.removing", "Tar bort certifikat i Root CA-certifikatlager" },
	    { "rootcertstore.cert.removed", "Tog bort certifikat i Root CA-certifikatlager som alias {0}" },
	    { "rootcertstore.cert.instore", "Kontrollerar om certifikatet finns i Root CA-certifikatlager" },
	    { "rootcertstore.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i Root CA-certifikatlager" },
	    { "rootcertstore.cert.iterator", "H\u00e4mta certifikatupprepare i Root CA-certifikatlager" },
{ "rootcertstore.cert.getkeystore", "H\u00e4mta nyckelarkivobjekt fr\u00e5n Root CA-certifikatlager" },
{ "roothttpscertstore.cert.getkeystore", "H\u00e4mta nyckelarkivobjekt fr\u00e5n Https Root CA-certifikatlager" },
	    { "rootcertstore.cert.verify.ok", "Certifikatet har bekr\u00e4ftats med Root CA-certifikat" },
	    { "rootcertstore.cert.verify.fail", "Bekr\u00e4ftelsen av certifikatet med Root CA-certifikat misslyckades" },
	{ "rootcertstore.cert.tobeverified", "Certifikat som ska verifieras:\n{0}" },
	{ "rootcertstore.cert.tobecompared", "J\u00e4mf\u00f6r certifikat med Root CA-certifikat:\n{0}" },

	    { "roothttpscertstore.cert.loading", "Laddar Root CA Https-certifikatfil fr\u00e5n {0}"},
	    { "roothttpscertstore.cert.loaded", "Laddade Root CA Https-certifikatfil fr\u00e5n {0}"},
	    { "roothttpscertstore.cert.noload", "Root CA Https-certifikatfil hittades inte: "},
	    { "roothttpscertstore.cert.saving", "Sparar Root CA Https-certifikat i {0}"},
	    { "roothttpscertstore.cert.saved", "Sparade Root CA Https-certifikat i "},
	    { "roothttpscertstore.cert.adding", "L\u00e4gger till certifikat i Root CA Https-certifikatlager"},
	    { "roothttpscertstore.cert.added", "Lade till certifikat i Root CA Https-certifikatlager som alias "},
	    { "roothttpscertstore.cert.removing", "Tar bort certifikat i Root CA Https-certifikatlager"},
	    { "roothttpscertstore.cert.removed", "Tog bort certifikat i Root CA Https-certifikatlager som alias "},
	    { "roothttpscertstore.cert.instore", "Kontrollerar om certifikatet finns i Root CA Https-certifikatlager"},
	    { "roothttpscertstore.cert.canverify", "Kontrollera om certifikat kan bekr\u00e4ftas med certifikat i Root CA Http-certifikatlager"},
	    { "roothttpscertstore.cert.iterator", "H\u00e4mta certifikatupprepare i Root CA Https-certifikatlager"},
	    { "roothttpscertstore.cert.verify.ok", "Certifikatet har bekr\u00e4ftats med Root CA Https-certifikat"},
	    { "roothttpscertstore.cert.verify.fail", "Bekr\u00e4ftelsen av certifikatet med Root CA Https-certifikat misslyckades"},
	{ "roothttpscertstore.cert.tobeverified", "Certifikat som ska verifieras:\n{0}" },
	{ "roothttpscertstore.cert.tobecompared", "J\u00e4mf\u00f6r certifikat med Root CA Https-certifikat:\n{0}" },

		{ "sessioncertstore.cert.loading", "Laddar certifikat fr\u00e5n JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.loaded", "Laddade certifikat fr\u00e5n JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.saving", "Sparar certifikat i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.saved", "Sparade certifikat i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.adding", "L\u00e4gger till certifikat i JPI-sessionscertifikatlager", },
	    { "sessioncertstore.cert.added", "Lade till certifikat i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.removing", "Ta bort certifikat i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.removed", "Tog bort certifikat i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.instore", "Kontrollerar om certifikatet finns i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i JPI-sessionscertifikatlager" },
	    { "sessioncertstore.cert.iterator", "H\u00e4mta certifikatupprepare i JPI-sessionscertifikatlager" },
{ "sessioncertstore.cert.getkeystore", "H\u00e4mta nyckelarkivobjekt fr\u00e5n JPI-sessionscertifikatlager" },
	    { "hostnameverifier.automation.ignoremismatch", "Automatisering: Ignorera v\u00e4rddatornamn som inte st\u00e4mmer \u00f6verens" },
        { "pluginclassloader.created_files", "Skapade {0} i cache." },
	    { "pluginclassloader.deleting_files", "Tar bort JAR-filer fr\u00e5n cachen." },
	    { "pluginclassloader.file", "   tar bort fr\u00e5n cachen {0}" },
	    { "pluginclassloader.empty_file", "{0} \u00e4r tom, tar bort fr\u00e5n cachen." },

           { "trustdecider.check.basicconstraints", "Det gick inte att kontrollera grundl\u00e4ggande begr\u00e4nsningar i certifikatet" },
           { "trustdecider.check.leafkeyusage", "Det gick inte att kontrollera l\u00f6vnyckeln i certifikatet" },
           { "trustdecider.check.signerkeyusage", "Det gick inte att kontrollera signaturnyckeln i certifikatet" },
           { "trustdecider.check.extensions", "Det gick inte att kontrollera kritiska till\u00e4gg i certifikatet" },
           { "trustdecider.check.signature", "Det gick inte att kontrollera signaturen i certifikatet" },
           { "trustdecider.check.basicconstraints.certtypebit", "Det gick inte att kontrollera bit av netscape-typ i certifikatet" },
           { "trustdecider.check.basicconstraints.extensionvalue", "Det gick inte att kontrollera netscape-till\u00e4ggsv\u00e4rdet i certifikatet" },
           { "trustdecider.check.basicconstraints.bitvalue", "Det gick inte att kontrollera  netscape-bitv\u00e4rdena 5,6,7 i certifikatet" },
           { "trustdecider.check.basicconstraints.enduser", "Det gick inte att kontrollera slutanv\u00e4ndarens akt som CA i certifikatet" },
           { "trustdecider.check.basicconstraints.pathlength", "Det gick inte att kontrollera begr\u00e4nsning f\u00f6r s\u00f6kv\u00e4gsl\u00e4ngd i certifikatet" },
           { "trustdecider.check.leafkeyusage.length", "Det gick inte att kontrollera l\u00e4ngden p\u00e5 nyckelanv\u00e4ndning i certifikatet" },
           { "trustdecider.check.leafkeyusage.digitalsignature", "Det gick inte att kontrollera digital signatur i certifikatet" },
           { "trustdecider.check.leafkeyusage.extkeyusageinfo", "Det gick inte att kontrollera anv\u00e4ndningsinfo f\u00f6r till\u00e4ggsnyckel i certifikatet" },
           { "trustdecider.check.leafkeyusage.certtypebit", "Det gick inte att kontrollera netscape-typbit i certifikatet" },
           { "trustdecider.check.signerkeyusage.lengthandbit", "Det gick inte att kontrollera l\u00e4ngd och bit i certifikatet" },
           { "trustdecider.check.signerkeyusage.keyusage", "Det gick inte att kontrollera nyckelanv\u00e4ndning i certifikatet" },
{ "trustdecider.check.canonicalize.updatecert", "Uppdatera Root-certifikat med certifikat i cacerts-filen" },
{ "trustdecider.check.canonicalize.missing", "L\u00e4gg till saknat Root-certifikat" },
{ "trustdecider.check.gettrustedcert.find", "S\u00f6k efter giltigt Root CA i cacerts-filen" },
{ "trustdecider.check.gettrustedissuercert.find", "S\u00f6k efter saknat giltigt Root CA i cacerts-filen" },
	    { "trustdecider.user.grant.session", "Anv\u00e4ndaren har gett beh\u00f6righet till koden endast i denna session" },
	    { "trustdecider.user.grant.forever", "Anv\u00e4ndaren har gett beh\u00f6righet till koden f\u00f6r alltid" },
	    { "trustdecider.user.deny", "Anv\u00e4ndaren har nekat beh\u00f6righet till koden" },
	    { "trustdecider.automation.trustcert", "Automatisering: Lita p\u00e5 RSA-certifikat vid signatur" },
	    { "x509trustmgr.automation.ignoreclientcert", "Automatisering: Ignorera icke tillf\u00f6rlitliga klientcertifikat" },
	    { "x509trustmgr.automation.ignoreservercert", "Automatisering: Ignorera icke tillf\u00f6rlitliga servercertifikat" },

	    { "appletcontext.audio.loaded", "Laddade ljudklipp: {0}" },
	    { "appletcontext.image.loaded", "Laddade bild: {0}" },

	    { "securitymgr.automation.printing", "Automatisering: Acceptera utskrift" },

	    { "classloaderinfo.referencing", "Refererar till classloader: {0}, refcount={1}" },
	    { "classloaderinfo.releasing", "Frisl\u00e4pper classloader: {0}, refcount={1}" },
	    { "classloaderinfo.caching", "Placerar classloader i cache: {0}" },
	    { "classloaderinfo.cachesize", "Aktuell cachestorlek f\u00f6r classloader: {0}" },
	    { "classloaderinfo.num", "Antal cachelagrade classloaders \u00f6ver {0}, unreference {1}" },

	    { "trace.listener.added", "Lade till sp\u00e5rningsavlyssnare: {0}" },
	    { "trace.listener.removed", "Tog bort sp\u00e5rningsavlyssnare: {0}" },
	
	    { "cookiehandler.cache", "Cookie-cache: " },
	    { "cookiehandler.server", "Server {0} beg\u00e4r set-cookie med \"{1}\"" },
	    { "cookiehandler.connect", "Ansluter {0} med cookie \"{1}\"" },
	    { "cookiehandler.ignore.setcookie", "Cookie-service \u00e4r ej tillg\u00e4nglig - bortse fr\u00e5n \"Set-Cookie\""},
	     { "cookiehandler.noservice", "Cookie-service \u00e4r ej tillg\u00e4nglig - anv\u00e4nd cache f\u00f6r att best\u00e4mma \"Cookie\""},

	    { "jsobject.eval", "Utv\u00e4rdera {0} = {1}" },
	    { "jsobject.call", "JSObject::call: namn={0}, url={1}, tillst\u00e5nd={2} "},
	    { "jsobject.eval.url.permission", "JSObject::eval({0}), url={1}, tillst\u00e5nd={2}" },
	    { "jsobject.getMember", "JSObject::getMember: namn={0}, url={1}, tilst\u00e5nd={2}" },
	    { "jsobject.setMember", "JSObject::setMember: namn={0}, url={1}, tillst\u00e5nd={2} " },
	     {"jsobject.removeMember", "JSObject::removeMember: namn={0}, url={1}, tillst\u00e5nd={2} " },
	      {"jsobject.getSlot", "JSObject::getSlot: {0}, url={0}, tillst\u00e5nd={2} " },
	       {"jsobject.setSlot", "JSObject::setSlot:{0}, url={0}, tillst\u00e5nd={2} " },

	    { "applet_install.ok", "Installationen av miniprogrammet \u00e4r klar." },
	    { "applet_install.fail", "Installationen av appleten misslyckades." },

	    { "optpkg.install.info", "Installera tillbeh\u00f6rspaket {0}" },
	    { "optpkg.install.fail", "Installationen av tillbeh\u00f6rspaketet misslyckades." },
	    { "optpkg.install.ok", "Installationen av tillbeh\u00f6rspaketet lyckades." },
	    { "optpkg.install.automation", "Automatisering: Acceptera installation av tillbeh\u00f6rspaket" },
	    { "optpkg.install.granted", "Anv\u00e4ndaren till\u00e5ter h\u00e4mtning av tillbeh\u00f6rspaket. H\u00e4mta fr\u00e5n {0}" },
	    { "optpkg.install.deny", "Anv\u00e4ndaren till\u00e5ter inte h\u00e4mtning av tillbeh\u00f6rspaket" },
	    { "optpkg.install.begin", "Installerar {0}" },
	    { "optpkg.install.java.launch", "Startar Java-installationsprogram" },
	    { "optpkg.install.java.launch.command", "Startar Java-installationsprogram via {0}" },
	    { "optpkg.install.native.launch", "Startar eget installationsprogram" },
	    { "optpkg.install.native.launch.fail.0", "Det g\u00e5r inte att k\u00f6ra {0}" },
	    { "optpkg.install.native.launch.fail.1", "\u00c5tkomst till {0} nekades" },
	    { "optpkg.install.raw.launch", "Installerar obearbetat tillbeh\u00f6rspaket" },
	    { "optpkg.install.raw.copy", "Kopierar obearbetat tillbeh\u00f6rspaket fr\u00e5n {0} till {1}" },
	    { "optpkg.install.error.nomethod", "Beroende tillbeh\u00f6rs-provider har inte installerats: Det g\u00e5r inte att h\u00e4mta "
	                         + " metoden addExtensionInstallationProvider" },
	    { "optpkg.install.error.noclass", "Beroende tillbeh\u00f6rs-provider har inte installerats: Det g\u00e5r inte att h\u00e4mta "
	                     + "klassen sun.misc.ExtensionDependency" },

	    { "dialogfactory.user.selected", "Anv\u00e4ndaren valde: {0}" },
	    { "dialogfactory.user.typed", "Anv\u00e4ndaren skrev: {0}" },

	    {"progress_dialog.downloading", "Plug-in: H\u00e4mtar..."},
	    {"progress_dialog.dismiss_button", "Avf\u00e4rda"},
        {"progress_dialog.dismiss_button.acceleratorKey", new Integer(KeyEvent.VK_A)},
	    {"progress_dialog.from", "fr\u00e5n"},

          { "applet_viewer.color_tag", "Felaktigt antal komponenter i {0}"},

	    {"progress_info.downloading", "H\u00e4mtar ytterligare JAR-fil(er)"},
	    {"progress_bar.preload", "F\u00f6rladdar JAR-filer: {0}"},

	    {"cache.size", "Cachestorlek: {0}"},
	    {"cache.cleanup", "Cachestorlek \u00e4r: {0} bytes, det \u00e4r n\u00f6dv\u00e4ndigt att st\u00e4da upp"},
	    {"cache.full", "Cachen \u00e4r full: tar bort filen: {0}"},
	    {"cache.inuse", "Kan inte ta bort filen {0} eftersom den anv\u00e4nds av applikationen"},
	    {"cache.notdeleted", "Kan inte ta bort filen {0}, den anv\u00e4nds eventuellt av denna och/eller andra applikationer"},
	    {"cache.out_of_date", "Cache-kopia av {0} \u00e4r f\u00f6r gammal\n Cache-kopia: {1}\n Serverkopia: {2}"},
	    {"cache.loading", "Laddar {0} fr\u00e5n cache"},
	    {"cache.cache_warning", "VARNING: Kan inte lagra i cache"},
	    {"cache.downloading", "Laddar ner {0} till cache"},
	    {"cache.cached_name", "Filnamn i cache: {0}"},
	    {"cache.load_warning", "VARNING: fel intr\u00e4ffade n\u00e4r {0} l\u00e4stes fr\u00e5n cache."},
	    {"cache.disabled", "Anv\u00e4ndaren har st\u00e4ngt av cachen"},
	    {"cache.minSize", "Cachen \u00e4r avst\u00e4ngd, dess gr\u00e4ns \u00e4r satt till {0}, \u00e5tminstone 5 MB b\u00f6r vara angivet"},
	    {"cache.directory_warning", "VARNING: {0} \u00e4r inte ett bibliotek. Cachen kommer att st\u00e4ngas av."},
	    {"cache.response_warning", "VARNING: Ov\u00e4ntat svar {0} f\u00f6r {1}.  Filen kommer att laddas ned p\u00e5 nytt."},
	    {"cache.enabled", "Cachen \u00e4r aktiverad"},
	    {"cache.location", "Plats: {0}" },
	    {"cache.maxSize", "St\u00f6rsta storlek: {0}"},
	    {"cache.create_warning", "VARNING: Kunde inte skapa cache-bibliotek {0}. Cachen kommer att st\u00e4ngas av."},
	    {"cache.read_warning", "VARNING: Kunde inte l\u00e4sa cache-bibliotek {0}. Cachen kommer att st\u00e4ngas av."},
	    {"cache.write_warning", "VARNING: Kunde inte skriva till cache-bibliotek {0}. Cachen kommer att st\u00e4ngas av."},
	    {"cache.compression", "Komprimeringsniv\u00e5: {0}"},
	    {"cache.cert_load", "Certifikat f\u00f6r {0} l\u00e4ses fr\u00e5n JAR-cache"},
	    {"cache.jarjar.invalid_file", ".jarjar-fil inneh\u00e5ller en fil som inte \u00e4r en .jar-fil"},
	    {"cache.jarjar.multiple_jar", ".jarjar-fil inneh\u00e5ller fler \u00e4n en .jar-fil"},
	    {"cache.version_checking", "Versionkontroll f\u00f6r {0}, angiven version \u00e4r {1}"},
	    {"cache.preloading", "F\u00f6rladdar fil {0}"},

	{ "cache_viewer.caption", "Detaljer - Cache" },
	    { "cache_viewer.refresh", "Uppdatera" },
	{ "cache_viewer.refresh.acceleratorKey", new Integer(KeyEvent.VK_U) },
	    { "cache_viewer.remove", "Ta bort" },
	{ "cache_viewer.remove.acceleratorKey", new Integer(KeyEvent.VK_T) },
	    { "cache_viewer.close", "St\u00e4ng" },
	{ "cache_viewer.close.acceleratorKey", new Integer(KeyEvent.VK_S) },
	    { "cache_viewer.name", "Namn" },
	    { "cache_viewer.type", "Typ"},
	    { "cache_viewer.size", "Storlek" },
	    { "cache_viewer.modify_date", "Senast \u00e4ndrad" },
	    { "cache_viewer.expiry_date", "F\u00f6rfallodatum" },
	    { "cache_viewer.url", "URL" },
	    { "cache_viewer.version", "Version" },
          { "cache_viewer.help.name", "Cachad jar-fils namn"},
	    { "cache_viewer.help.type", "Cachad jar-fils typ"},
          { "cache_viewer.help.size", "Cachad jar-fils storlek"},
          { "cache_viewer.help.modify_date", "Cachad jar-fils senaste \u00e4ndringsdatum"},
          { "cache_viewer.help.expiry_date", "Cachad jar-fils f\u00f6rfallodatum"},
          { "cache_viewer.help.url", "Jar-fils nerladdnings-URL"},
          { "cache_viewer.help.version","Jar-fils cache-version"},
	{ "cache_viewer.delete.text", "<html><b>Fil har inte tagits bort</b></html>{0} kan vara i bruk.\n" },
	{ "cache_viewer.delete.caption", "Fel - Cache" },
	    { "cache_viewer.type.zip", "Jar"},
	    { "cache_viewer.type.class", "Klass"},
	    { "cache_viewer.type.wav", "Wav-ljud"},
	    { "cache_viewer.type.au", "Au-ljud"},
	    { "cache_viewer.type.gif", "Gif-bild"},
	    { "cache_viewer.type.jpg", "Jpeg-bild"}, 

	    { "net.proxy.loading.ie", "Laddar proxykonfiguration fr\u00e5n Internet Explorer ..."},
	    { "net.proxy.loading.ns", "Laddar proxykonfiguration fr\u00e5n Netscape Navigator ..."},
	    { "net.proxy.loading.userdef", "Laddar anv\u00e4ndardefinierad proxykonfiguration ..."},
	    { "net.proxy.loading.direct", "Laddar direkt proxykonfiguration ..."},
	    { "net.proxy.loading.manual", "Laddar manuell proxykonfiguration ..."},
	    { "net.proxy.loading.auto",   "Laddar automatisk proxykonfiguration ..."},
	    { "net.proxy.loading.browser",   "Laddar webbl\u00e4sarbaserad proxykonfiguration ..."},
	    { "net.proxy.loading.manual.error", "Det g\u00e5r inte att anv\u00e4nda manuell proxykonfiguration - \u00e5terv\u00e4nder till DIRECT"},
	    { "net.proxy.loading.auto.error", "Det g\u00e5r inte att anv\u00e4nda automatisk proxykonfiguration - \u00e5terv\u00e4nder till MANUAL"},
	    { "net.proxy.loading.done", "Klar."},
	    { "net.proxy.browser.pref.read", "L\u00e4ser fil med anv\u00e4ndarinst\u00e4llningar fr\u00e5n {0}"},
	    { "net.proxy.browser.proxyEnable", "    Aktivera proxy: {0}"},
	    { "net.proxy.browser.proxyList",     "    Proxylista: {0}"},
	    { "net.proxy.browser.proxyOverride", "    Proxy-ers\u00e4ttningar: {0}"},
	    { "net.proxy.browser.autoConfigURL", "    URL f\u00f6r automatisk konfiguration: {0}"},
	{ "net.proxy.browser.smartConfig", "Pinga proxy-servern {0} p\u00e5 port {1}"},
        { "net.proxy.browser.connectionException", "Proxy-server {0} p\u00e5 port {1} kan inte n\u00e5s "},
                      { "net.proxy.ns6.regs.exception", "Fel vid l\u00e4sning av registerfil: {0}"},
	    { "net.proxy.pattern.convert", "Konvertera lista \u00f6ver proxy-ers\u00e4ttningar till regeluttryck: "},
	    { "net.proxy.pattern.convert.error", "Det g\u00e5r inte att konvertera lista \u00f6ver proxy-ers\u00e4ttningar till regeluttryck - ignorera"},
	    { "net.proxy.auto.download.ins", "H\u00e4mtar INS-fil fr\u00e5n {0}" },
	    { "net.proxy.auto.download.js", "H\u00e4mtar automatisk proxyfil fr\u00e5n {0}" },
	    { "net.proxy.auto.result.error", "Det g\u00e5r inte att fastst\u00e4lla proxy-inst\u00e4llning fr\u00e5n utv\u00e4rdering - \u00e5terv\u00e4nder till DIRECT"},
	    { "net.proxy.service.not_available", "Proxy-service \u00e4r inte tillg\u00e4nglig f\u00f6r {0} - \u00e5terv\u00e4nder till DIRECT"},

          { "lifecycle.applet.found", "Hittade tidigare stoppad applet i livscykelcache"},
          { "lifecycle.applet.support", "Applet st\u00f6der modellen f\u00f6r \u00e4rvd livscykel - l\u00e4gg applet till livscykelcache"},
          { "lifecycle.applet.cachefull", "Livscykelcachen \u00e4r full - ta bort senast anv\u00e4nda appletar"},

	{ "com.method.ambiguous", "Det g\u00e5r inte att v\u00e4lja en metod, parametrarna \u00e4r inte entydiga" },
	{ "com.method.notexists", "{0} :det finns ingen s\u00e5dan metod" },
	{ "com.notexists", "{0} :det finns ingen s\u00e5dan metod/egenskap" },
	{ "com.method.invoke", "Anropar metod: {0}" },
	{ "com.method.jsinvoke", "Anropar JS-metod: {0}" },
	{ "com.method.argsTypeInvalid", "Parametrarna kan inte konverteras till de n\u00f6dv\u00e4ndiga typerna" },
	{ "com.method.argCountInvalid", "Antalet argument \u00e4r felaktigt" },
	{ "com.field.needsConversion", "M\u00e5ste konverteras: {0} --> {1}" },
	{ "com.field.typeInvalid", " kan inte konverteras till typ: {0}" },
	{ "com.field.get", "H\u00e4mtar egenskap: {0}" },
	{ "com.field.set", "St\u00e4ller in egenskap: {0}" },

	{"about.java.version", "Version"},
	{"about.prompt.info", "Mer information finns p\u00e5"},
	{"about.home.link", "http://www.java.com"},
	{"about.option.close", "St\u00e4ng"},
	{"about.option.close.acceleratorKey", new Integer(KeyEvent.VK_S) },
	{"about.legal.note", "Copyright 2003 Sun Microsystems, Inc. Med ensamr\u00e4tt. Anv\u00e4ndningen reglera " +
			     "av villkoren i licensavtalet. Program fr\u00e5n andra f\u00f6retag, t ex teckensnittsteknik, " +
			     "\u00e4r copyrightskyddade och licensieras av Suns leverant\u00f6rer. Vissa delar skyddas " +
			     "genom copyright som tillh\u00f6r Eastman Kodak Company 1992. Produkten inneh\u00e5ller " +
			     "kod som licensieras fr\u00e5n RSA Data Security. " +
			     "Sun, Sun Microsystems, Sun-logotypen, Java, Solaris och J2SE \u00e4r varum\u00e4rken " +
			     "eller registrerade varum\u00e4rken som tillh\u00f6r Sun Microsystems, Inc. i USA och " +
			     "andra l\u00e4nder. Alla SPARC-varum\u00e4rken anv\u00e4nds under licens och \u00e4r varum\u00e4rken " +
			     "eller registrerade varum\u00e4rken som tillh\u00f6r SPARC International, Inc. i " +
			     "USA och andra l\u00e4nder. Nationella ink\u00f6p: Kommersiell programvara - Villkor " +
			     "f\u00f6r standardlicens f\u00f6r anv\u00e4ndare inom den offentliga f\u00f6rvaltningen."}
     };
}


