/*
 * @(#)Activator_es.java	1.41 03/05/11 
 *
 * Copyright 2003 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
 
package sun.plugin.resources;

import java.util.ListResourceBundle;
import java.awt.event.KeyEvent;
/**
 * Spanish version of Activator strings.
 *
 * @author Jerome Dochez
 */

public class Activator_es extends ListResourceBundle {

    public Object[][] getContents() {
        return contents;
    }

    static final Object[][] contents = {
	{ "panel.caption", "Panel de control de Java(TM) Plug-in" }, 
    	{ "product_name", "Java (TM) Plug-in" },
    	{ "version", "Versi\u00f3n" },
    	{ "default_vm_version", "Versi\u00f3n de la m\u00e1quina virtual predeterminada" },
    	{ "using_jre_version", "Usar versi\u00f3n JRE" },
    	{ "user_home_dir", "Directorio local del usuario" },
    	{ "user_overriden_browser", "El usuario ha alterado los valores de delegado del navegador." },
    	{ "proxy_configuration", "Configuraci\u00f3n del delegado: " },
    	{ "browser_config", "Configuraci\u00f3n del delegado del navegador" },
    	{ "auto_config", "Configuraci\u00f3n autom\u00e1tica del delegado" },
    	{ "manual_config", "Configuraci\u00f3n manual" },
   	 { "no_proxy", "Sin delegado" },
   	 { "proxy_is", "Delegado: " },
    	{ "proxy_override_is", "Alteraciones del delegado: " },
    	{ "loading", "Cargando {0}" },
    	{ "java_applet", "Subprograma de Java" },
        { "failed", "Ha fallado la carga del applet de Java..." },
        { "image_failed", "No se ha podido crear la imagen definida por el usuario.  Comprobar nombre del archivo de imagen." },
    	{ "java_bean", "JavaBeans" },
    	{ "java_not_enabled", "Java no habilitado" },
        { "exception", "Excepci\u00f3n: {0}" },

    	{ "net.connect.no_proxy", "Conectando {0} sin delegado" },
   	 { "net.connect.proxy_is", "Conectando {0} con delegado={1}" },

    	{ "bean_code_and_ser", "Bean no puede tener definido CODE y JAVA_OBJECT " },
    	{ "status_applet", "Subprograma {0} {1}" },
  
    	// Resources associated with SecurityManager print Dialog:
	{ "print.caption", "Se necesita confirmaci\u00f3n - Imprimir" },
    	{ "print.message", new String[]{
		"<html><b>Solicitud de impresi\u00f3n</b></html>El subprograma va a iniciar la impresi\u00f3n. \u00bfDesea proseguir?"}},
	{ "print.checkBox", "No mostrar de nuevo este cuadro de di\u00e1logo" },
	{ "print.buttonYes", "S\u00ed" },
	{ "print.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_S)},
	{ "print.buttonNo", "No" },
	{ "print.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},

	{ "https_dialog.caption", "Advertencia - HTTPS" },
	{ "https_dialog.text", "<html><b>Discordancia de nombres de sistema</b></html>El nombre de sistema en el certificado de seguridad del servidor no coincide con el nombre del servidor." 
			     + "\n\nNombre de sistema del URL: {0}"
			     + "\nNombre de sistema en el certificado: {1}"
			     + "\n\n\u00bfDesea proseguir?" },
    { "https_dialog.unknown.host", "Sistema desconocido" },
	
	{ "security_dialog.caption", "Advertencia - Seguridad" },
    { "security_dialog.text0", "\u00bfDesea instalar y ejecutar el subprograma firmado distribuido por \"{0}\"?"
  				+ "\n\nAutenticidad del editor verificada por: \"{1}\"" },  
    { "security_dialog_https.text0", "\u00bfDesea aceptar este certificado del sitio web \"{0}\" para el intercambio de informaci\u00f3n cifrada?"
				 + "\n\nAutenticidad del editor verificada por: \"{1}\"" },
    { "security_dialog.text1", "\nPrecauci\u00f3n: \"{0}\" afirma que este contenido es seguro. S\u00f3lo debe instalar/visualizar el contenido si conf\u00eda en \"{1}\" \n\n" },
    { "security_dialog.unknown.issuer", "Emisor desconocido" },
    { "security_dialog.unknown.subject", "Asunto desconocido" },
	{ "security_dialog.certShowName", "{0}({1})" },
    { "security_dialog.rootCANotValid", "El certificado de seguridad lo emiti\u00f3 una compa\u00f1\u00eda que no es de confianza." },
    { "security_dialog.rootCAValid", "El certificado de seguridad lo emiti\u00f3 una compa\u00f1\u00eda de confianza." },
    { "security_dialog.timeNotValid", "El certificado de seguridad ha caducado o a\u00fan no es v\u00e1lido." },
    { "security_dialog.timeValid", "El certificado de seguridad no ha caducado y a\u00fan es v\u00e1lido." },
	{ "security_dialog.buttonAlways", "Siempre" },
        { "security_dialog.buttonAlways.acceleratorKey", new Integer(KeyEvent.VK_I)},
	{ "security_dialog.buttonYes", "S\u00ed" },
	{ "security_dialog.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_S)},
        { "security_dialog.buttonNo", "No" },
	{ "security_dialog.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "security_dialog.buttonViewCert", "M\u00e1s detalles" },	
        { "security_dialog.buttonViewCert.acceleratorKey", new Integer(KeyEvent.VK_M)},
        
	{ "cert_dialog.caption", "Detalles - Certificado" },
	{ "cert_dialog.certpath", "Ruta del certificado" },
    { "cert_dialog.field.Version", "Versi\u00f3n" },
    { "cert_dialog.field.SerialNumber", "N\u00famero de serie" },
    { "cert_dialog.field.SignatureAlg", "Algoritmo de firma" },
    { "cert_dialog.field.Issuer", "Emisor" },
    { "cert_dialog.field.EffectiveDate", "Fecha efectiva" },
    { "cert_dialog.field.ExpirationDate", "Fecha de caducidad" },
    { "cert_dialog.field.Validity", "Validez" },
    { "cert_dialog.field.Subject", "Asunto" },
    { "cert_dialog.field.Signature", "Firma" },
    { "cert_dialog.field", "Campo" },
    { "cert_dialog.value", "Valor" },

        { "cert_dialog.close", "Cerrar" },
	{ "cert_dialog.close.acceleratorKey", new Integer(KeyEvent.VK_C) },

	{ "net.authenticate.caption", "Se necesita contrase\u00f1a - Conexi\u00f3n en red"},
	{ "net.authenticate.label", "<html><b>Introduzca su nombre de usuario y su contrase\u00f1a:</b></html>"},
    	{ "net.authenticate.resource", "Recurso:" },
    	{ "net.authenticate.username", "Nombre de usuario:" },
  	 { "net.authenticate.password", "Contrase\u00f1a:" },
  	 { "net.authenticate.firewall", "Cortafuegos:" },
  	 { "net.authenticate.realm", "\u00c1mbito:" },
   	 { "net.authenticate.scheme", "Esquema:" },
   	 { "net.authenticate.unknownSite", "Sitio desconocido" },

    { "console.caption", "Consola de Java" },
    { "console.clear", "Borrar" },
    { "console.clear.acceleratorKey", new Integer(KeyEvent.VK_B)},
    { "console.close", "Cerrar" },
    { "console.close.acceleratorKey", new Integer(KeyEvent.VK_C) },
    { "console.copy", "Copiar" },
    { "console.copy.acceleratorKey", new Integer(KeyEvent.VK_O) },

	{ "optpkg.cert_expired", "<html><b>El certificado ha caducado</b></html>Se ha cancelado la instalaci\u00f3n del paquete opcional.\n" },
	{ "optpkg.cert_notyieldvalid", "<html><b>El certificado no es v\u00e1lido</b></html>Se ha cancelado la instalaci\u00f3n del paquete opcional.\n" },
	{ "optpkg.cert_notverify", "<html><b>El certificado no se ha verificado</b></html>Se ha cancelado la instalaci\u00f3n del paquete opcional.\n" },
	{ "optpkg.general_error", "<html><b>Excepci\u00f3n general</b></html>Se ha cancelado la instalaci\u00f3n del paquete opcional.\n" },
	{ "optpkg.caption", "Advertencia - Paquete opcional" },
	{ "optpkg.installer.launch.wait", "<html><b>Instalaci\u00f3n del paquete opcional</b></html>Haga clic en Aceptar para continuar la carga del subprograma cuando se haya instalado el instalador del paquete opcional.\n" },
	{ "optpkg.installer.launch.caption", "Instalaci\u00f3n en curso - Paquete opcional"},
	{ "optpkg.prompt_user.new_spec.text", "<html><b>Solicitud de descarga</b></html>El subprograma necesita una versi\u00f3n m\u00e1s reciente (especificaci\u00f3n {0}) del paquete opcional \"{1}\" de {2}\n\nDesea proseguir?" },
	{ "optpkg.prompt_user.new_impl.text", "<html><b>Solicitud de descarga</b></html>El subprograma necesita una versi\u00f3n m\u00e1s reciente (implementaci\u00f3n {0}) del paquete opcional \"{1}\" de {2}\n\n\u00bfDesea proseguir?" },
	{ "optpkg.prompt_user.new_vendor.text", "<html><b>Solicitud de descarga</b></html>El subprograma necesita el ({0}) de paquete opcional \"{1}\" {2} de {3}\n\n\u00bfDesea proseguir?" },
	{ "optpkg.prompt_user.default.text", "<html><b>Solicitud de descarga</b></html>El subprograma necesita que se instale el paquete opcional \"{0}\" de {1}\n\n\u00bfDesea proseguir?" },

	{ "rsa.cert_expired", "<html><b>El certificado ha caducado</b></html>El c\u00f3digo se tratar\u00e1 como no firmado.\n" },
	{ "rsa.cert_notyieldvalid", "<html><b>El certificado no es v\u00e1lido</b></html>El c\u00f3digo se tratar\u00e1 como no firmado.\n" },
	{ "rsa.general_error", "<html><b>El certificado no se ha verificado</b></html>El c\u00f3digo se tratar\u00e1 como no firmado.\n" },

	{ "usability.confirmDialogTitle", "Se necesita confirmaci\u00f3n - Java" },
	{ "usability.inputDialogTitle", "Se necesita informaci\u00f3n - Java" },
	{ "usability.messageDialogTitle", "Mensaje - Java" },
	{ "usability.exceptionDialogTitle", "Error - Java" },
	{ "usability.optionDialogTitle", "Opci\u00f3n - Java" },
	{ "usability.aboutDialogTitle", "Acerca de - Java" },
	{ "usability.confirm.yes", "S\u00ed" },
        { "usability.confirm.yes.acceleratorKey", new Integer(KeyEvent.VK_S)},
	{ "usability.confirm.no", "No" },
        { "usability.confirm.no.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "usability.moreInfo", "M\u00e1s detalles" },	
        { "usability.moreInfo.acceleratorKey", new Integer(KeyEvent.VK_M)},
        { "usability.lessInfo", "Menos detalles" },	
        { "usability.lessInfo.acceleratorKey", new Integer(KeyEvent.VK_E)},
	{ "usability.java.home.link", "http://www.java.com" },

	{ "usability.general_error", "<html><b>Excepci\u00f3n general</b></html>" },
	{ "usability.net_error", "<html><b>Excepci\u00f3n de conexi\u00f3n en red</b></html>" },
	{ "usability.security_error", "<html><b>Excepci\u00f3n de seguridad</b></html>" },
	{ "usability.ext_error", "<html><b>Excepci\u00f3n de paquete opcional</b></html>" },

    { "usability.menu.show_console", "Mostrar consola Java" },
    { "usability.menu.hide_console", "Ocultar consola Java" },
    { "usability.menu.about", "Acerca del Java Plug-in" },
    { "usability.menu.copy", "Copiar" },
	{ "usability.menu.open_console", "Abrir consola de Java" },
	{ "usability.menu.about_java", "Acerca de Java(TM)" },

	{ "proxy.error_caption", "Error - Configuraci\u00f3n del proxy" },
	{ "proxy.prefsfile.nsreg_error", "<html><b>No se puede recuperar los valores del proxy</b></html>Retroceder a otra configuraci\u00f3n del proxy.\n" },

	{ "cache.error.text", "<html><b>Error de antememoria</b></html>No se puede guardar ni actualizar archivos en la antememoria"},
	{ "cache.error.caption", "Error - Antememoria" },
	{ "cache.version_format_error", "{0} no est\u00e1 en el formato xxxx.xxxx.xxxx.xxxx, donde x es un d\u00edgito hexadecimal" },
    { "cache.version_attrib_error", "El n\u00famero de atributos especificados en \'cache_archive\' no coincide con los de \'cache_version\'" },
	{ "cache.header_fields_missing", "No se conoce la hora de modificaci\u00f3n ni/o el valor de caducidad.  El archivo JAR no se colocar\u00e1 en la antememoria."},

    { "applet.progress.load", "Cargando miniaplicaci\u00f3n..." },
    { "applet.progress.init", "Inicializando miniaplicaci\u00f3n..." },
    { "applet.progress.start", "Iniciando miniaplicaci\u00f3n..." },
    { "applet.progress.stop", "Deteniendo miniaplicaci\u00f3n..." },
    { "applet.progress.destroy", "Destruyendo miniaplicaci\u00f3n..." },
    { "applet.progress.dispose", "Desechando miniaplicaci\u00f3n..." },
    { "applet.progress.quit", "Saliendo de miniaplicaci\u00f3n..." },
    { "applet.progress.stoploading", "Se detuvo la carga..." },
    { "applet.progress.interrupted", "Se interrumpi\u00f3 el subproceso..." },
    { "applet.progress.joining", "Uniendo el subproceso de la miniaplicaci\u00f3n..." },
    { "applet.progress.joined", "Unido el subproceso de la miniaplicaci\u00f3n..." },
    { "applet.progress.loadImage", "Carga de imagen " },
    { "applet.progress.loadAudio", "Carga de audio " },
    { "applet.progress.findinfo.0", "Buscando informaci\u00f3n..." },
    { "applet.progress.findinfo.1", "Terminado..." },
    { "applet.progress.timeout.wait", "Tiempo de espera..." },
    { "applet.progress.timeout.jointing", "Uniendo..." },
    { "applet.progress.timeout.jointed", "Uni\u00f3n terminada..." },


    { "console.menu.text.top", "----------------------------------------------------\n" },
    { "console.menu.text.c", "c:   borrar ventana de consola\n" },
    { "console.menu.text.f", "f:   finalizar objetos en la cola de finalizaci\u00f3n\n" },
    { "console.menu.text.g", "g:   liberaci\u00f3n de recursos\n" },
    { "console.menu.text.h", "h:   presentar este mensaje de ayuda\n" },
    { "console.menu.text.j", "j:   volcar datos jcov\n"},
    { "console.menu.text.l", "l:   volcar lista del cargador de clases\n" },
    { "console.menu.text.m", "m:   imprimir sintaxis de memoria\n" },
    { "console.menu.text.o", "o:   activar registro\n" },
    { "console.menu.text.p", "p:   recargar configuraci\u00f3n delegada\n" },
    { "console.menu.text.q", "q:   ocultar consola\n" },
    { "console.menu.text.r", "r:   recargar configuraci\u00f3n de norma\n" },
    { "console.menu.text.s", "s:   volcar propiedades del sistema\n" },
    { "console.menu.text.t", "t:   volcar lista de subproceso\n" },
    { "console.menu.text.v", "v:   volcar pila de subprocesos\n" },
    { "console.menu.text.x", "x:   borrar antememoria del cargador de clases\n" },
    { "console.menu.text.0", "0-5: establecer nivel de rastreo a <n>\n" },
    { "console.menu.text.tail", "----------------------------------------------------\n" },
    { "console.done", "Terminado." },
    { "console.trace.level.0", "Nivel de rastreo establecido a 0: ninguno ... terminado." },
    { "console.trace.level.1", "Nivel de rastreo establecido a 1: b\u00e1sico ... terminado." },
    { "console.trace.level.2", "Nivel de rastreo establecido a 2: b\u00e1sico, red ... terminado." },
    { "console.trace.level.3", "Nivel de rastreo establecido a 3: b\u00e1sico, red, seguridad ... terminado." },
    { "console.trace.level.4", "Nivel de rastreo establecido a 4: b\u00e1sico, red, seguridad, ext ... terminado." },
    { "console.trace.level.5", "Nivel de rastreo establecido a 5: b\u00e1sico, red, seguridad, ext, Liveconnect ... terminado." },
    { "console.log", "Registro establecido a : " },
    { "console.completed", " .... terminado." },
    { "console.dump.thread", "Volcar lista de subproceso ...\n" },
	{ "console.dump.stack", "Volcar pila de subprocesos ...\n" },
    { "console.dump.properties", "Volcar propiedades del sistema ...\n" },
    { "console.clear.classloader", "Borrar antememoria del cargador de clases .... terminado." },
    { "console.reload.policy", "Recargar configuraci\u00f3n de norma" },
    { "console.reload.proxy", "Recargar configuraci\u00f3n delegada ...." },
    { "console.gc", "Liberaci\u00f3n de recursos" },
    { "console.finalize", "Finalizar objetos en la cola de finalizaci\u00f3n" },
    { "console.memory", "Memoria: {0}K  Libre: {1}K  ({2}%)" },
    { "console.jcov.error", "Error de runtime de Jcov: compruebe si ha especificado la opci\u00f3n jcov adecuada\n"},
    { "console.jcov.info", "Datos jcov volcados con \u00e9xito\n"},

    { "modality.register", "Modalidad de receptor registrada" },
    { "modality.unregister", "Modalidad de receptor no registrada" },
    { "modality.pushed", "Modalidad impuesta" },
    { "modality.popped", "Modalidad extra\u00edda" },

    { "progress.listener.added", "Receptor de progreso agregado: {0}" },
    { "progress.listener.removed", "Receptor de progreso eliminado: {0}" },

    { "liveconnect.UniversalBrowserRead.enabled", "JavaScript: UniversalBrowserRead habilitado" },
    { "liveconnect.java.system", "JavaScript: llamada de c\u00f3digo del sistema Java" },
    { "liveconnect.same.origin", "JavaScript: el llamante y el destinatario de la llamada tienen el mismo origen" },
    { "liveconnect.default.policy", "JavaScript: norma de seguridad predeterminada = {0}" },
    { "liveconnect.UniversalJavaPermission.enabled", "JavaScript: UniversalJavaPermission habilitado" },
    { "liveconnect.wrong.securitymodel", "Ya no se admite el modelo de seguridad de Netscape.\n"
                         + "En su lugar, migre al modelo de seguridad de Java 2.\n" },

    { "jpicertstore.cert.loading", "Carga de certificados JPI desde {0}" },
    { "jpicertstore.cert.loaded", "Certificados JPI cargados desde {0}" },
    { "jpicertstore.cert.saving", "Guardar certificados JPI en {0}" },
    { "jpicertstore.cert.saved", "Certificados JPI guardados en {0}" },
    { "jpicertstore.cert.adding", "Adici\u00f3n de certificado al almac\u00e9n permanente de certificados JPI", },
    { "jpicertstore.cert.added", "Certificado agregado como alias {0} al almac\u00e9n permanente de certificados JPI " },
    { "jpicertstore.cert.removing", "Eliminaci\u00f3n de certificado del almac\u00e9n permanente de certificados JPI" },
    { "jpicertstore.cert.removed", "Certificado eliminado como alias {0} del almac\u00e9n permanente de certificados JPI " },
    { "jpicertstore.cert.instore", "Comprobar si el certificado est\u00e1 en el almac\u00e9n permanente de certificados JPI" },
    { "jpicertstore.cert.canverify", "Comprobar si se puede verificar el certificado por medio del almac\u00e9n permanente de certificados JPI" },
    { "jpicertstore.cert.iterator", "Obtener iterador de certificados en el almac\u00e9n permanente de certificados JPI" },
{ "jpicertstore.cert.getkeystore", "Obtener objeto de almac\u00e9n clave del almac\u00e9n de certificados JPI" },

    { "jpihttpscertstore.cert.loading", "Carga de certificados JPI Https desde {0}" },
    { "jpihttpscertstore.cert.loaded", "Certificados JPI Https cargados desde {0}" },
    { "jpihttpscertstore.cert.saving", "Guardar certificados JPI Https en {0}" },
    { "jpihttpscertstore.cert.saved", "Certificados JPI Https guardados en {0}" },
    { "jpihttpscertstore.cert.adding", "Adici\u00f3n de certificado Https al almac\u00e9n permanente de certificados JPI", },
    { "jpihttpscertstore.cert.added", "Certificado Https agregado como alias {0} del almac\u00e9n permanente de certificados JPI " },
    { "jpihttpscertstore.cert.removing", "Eliminaci\u00f3n de certificado Https del almac\u00e9n permanente de certificados JPI" },
    { "jpihttpscertstore.cert.removed", "Certificado Https eliminado como alias{0}  del almac\u00e9n permanente de certificados JPI " }, 
    { "jpihttpscertstore.cert.instore", "Comprobar si el certificado Https est\u00e1 en el almac\u00e9n permanente de certificados JPI" },
    { "jpihttpscertstore.cert.canverify", "Comprobar si se puede verificar el certificado Https por medio del almac\u00e9n permanente de certificados JPI" },
    { "jpihttpscertstore.cert.iterator", "Obtener iterador de certificados Https en el almac\u00e9n permanente de certificados JPI" },
{ "jpihttpscertstore.cert.getkeystore", "Obtener objeto de almac\u00e9n clave del almac\u00e9n de certificados Https"},
    { "rootcertstore.cert.loading", "Carga de certificados CA ra\u00edz desde {0}" },
    { "rootcertstore.cert.loaded", "Certificados CA ra\u00edz cargados desde {0}" },
    { "rootcertstore.cert.noload", "No se ha encontrado el archivo de los certificados CA ra\u00edz: {0}" },
    { "rootcertstore.cert.saving", "Guardar certificados CA ra\u00edz en {0}" },
    { "rootcertstore.cert.saved", "Certificados CA ra\u00edz guardados en {0}" },
    { "rootcertstore.cert.adding", "Adici\u00f3n de certificado en el almac\u00e9n de certificados CA ra\u00edz", },
    { "rootcertstore.cert.added", "Certificado agregado como alias {0} en el almac\u00e9n de certificados CA ra\u00edz " },
    { "rootcertstore.cert.removing", "Eliminaci\u00f3n de certificado del almac\u00e9n de certificados CA ra\u00edz" },
    { "rootcertstore.cert.removed", "Certificado eliminado como alias {0} en el almac\u00e9n de certificados CA ra\u00edz " },
    { "rootcertstore.cert.instore", "Comprobar si el certificado est\u00e1 en el almac\u00e9n de certificados CA ra\u00edz" },
    { "rootcertstore.cert.canverify", "Comprobar si se puede verificar el certificado por medio de los certificados del almac\u00e9n de certificados CA ra\u00edz" },
    { "rootcertstore.cert.iterator", "Obtener iterador de certificados en el almac\u00e9n de certificados CA ra\u00edz" },
{ "rootcertstore.cert.getkeystore", "Obtener objeto de almac\u00e9n clave del almac\u00e9n de certificados CA ra\u00edz" },
{ "roothttpscertstore.cert.getkeystore", "Obtener objeto de almac\u00e9n clave del almac\u00e9n de certificados CA ra\u00edz Https" },
    { "rootcertstore.cert.verify.ok", "El certificado se ha verificado correctamente con certificados CA ra\u00edz" },
    { "rootcertstore.cert.verify.fail", "El certificado no se ha verificado satisfactoriamente con los certificados CA ra\u00edz" },
	{ "rootcertstore.cert.tobeverified", "Certificado que debe verificarse:\n{0}" },
	{ "rootcertstore.cert.tobecompared", "Comparando certificado con el certificado CA ra\u00edz:\n{0}" },

    { "roothttpscertstore.cert.loading", "Carga de certificados Https CA ra\u00edz desde {0}" },
    { "roothttpscertstore.cert.loaded", "Certificados Https CA ra\u00edz cargados desde {0}" },
    { "roothttpscertstore.cert.noload", "No se ha encontrado el archivo de los certificados Https CA ra\u00edz: " },
    { "roothttpscertstore.cert.saving", "Guardar certificados Https CA ra\u00edz en  {0}" },
    { "roothttpscertstore.cert.saved", "Certificados Https CA ra\u00edz guardados en  " },
    { "roothttpscertstore.cert.adding", "Adici\u00f3n de certificado en el almac\u00e9n de certificados Https CA ra\u00edz", },
    { "roothttpscertstore.cert.added", "Certificado agregado como alias en el almac\u00e9n de certificados Https CA ra\u00edz" },
    { "roothttpscertstore.cert.removing", "Eliminaci\u00f3n de certificado del almac\u00e9n de certificados Https CA ra\u00edz" },
    { "roothttpscertstore.cert.removed", "Certificado eliminado como alias en el almac\u00e9n de certificados Https CA ra\u00edz" }, 
    { "roothttpscertstore.cert.instore", "Comprobar si el certificado est\u00e1 en el almac\u00e9n de certificados Https CA ra\u00edz" },
    { "roothttpscertstore.cert.canverify", "Comprobar si se puede verificar el certificado por medio de los certificados del almac\u00e9n de certificados Https CA ra\u00edz" },
    { "roothttpscertstore.cert.iterator", "Obtener iterador de certificados en el almac\u00e9n de certificados Https CA ra\u00edz" },
    { "roothttpscertstore.cert.verify.ok", "El certificado se ha verificado correctamente con certificados Https CA ra\u00edz" },
    { "roothttpscertstore.cert.verify.fail", "El certificado no se ha verificado satisfactoriamente con los certificados Https CA ra\u00edz" },
	{ "roothttpscertstore.cert.tobeverified", "Certificado que debe verificarse:\n{0}" },
	{ "roothttpscertstore.cert.tobecompared", "Comparando certificado con el certificado Https CA ra\u00edz:\n{0}" },

    { "sessioncertstore.cert.loading", "Carga de certificados del almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.loaded", "Certificados cargados del almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.saving", "Guardar certificados en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.saved", "Certificados guardados en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.adding", "Adici\u00f3n de certificados en el almac\u00e9n de certificados de la sesi\u00f3n JPI", },
    { "sessioncertstore.cert.added", "Certificados agregados en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.removing", "Eliminaci\u00f3n de certificado en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.removed", "Certificado eliminado en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.instore", "Comprobar si el certificado est\u00e1 en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.canverify", "Comprobar si se puede verificar el certificado por medio de los certificados del almac\u00e9n de certificados de la sesi\u00f3n JPI" },
    { "sessioncertstore.cert.iterator", "Obtener iterador de certificados en el almac\u00e9n de certificados de la sesi\u00f3n JPI" },
{ "sessioncertstore.cert.getkeystore", "Obtener objeto de almac\u00e9n clave del almac\u00e9n de certificados de sesi\u00f3n JPI" },
    { "hostnameverifier.automation.ignoremismatch", "Automatizaci\u00f3n: Ignorar discrepancia en nombre del sistema" },
    { "pluginclassloader.created_files", "Creado (0) en la antememoria." },
    { "pluginclassloader.deleting_files", "Supresi\u00f3n de archivos JAR de la antememoria." },
    { "pluginclassloader.file", "   supresi\u00f3n desde la antememoria {0}" },
    { "pluginclassloader.empty_file", "{0} est\u00e1 vac\u00edo, suprimir de la antememoria." },

	{ "trustdecider.check.basicconstraints", "La comprobaci\u00f3n de restricciones b\u00e1sicas ha fallado en el certificado" },
	{ "trustdecider.check.leafkeyusage", "La comprobaci\u00f3n del uso de la clave de hoja ha fallado en el certificado" },
	{ "trustdecider.check.signerkeyusage", "La comprobaci\u00f3n del uso de la clave del firmante ha fallado en el certificado" },
	{ "trustdecider.check.extensions", "La comprobaci\u00f3n de extensiones cr\u00edticas ha fallado en el certificado" },
	{ "trustdecider.check.signature", "La comprobaci\u00f3n de firma ha fallado en el certificado" },
	{ "trustdecider.check.basicconstraints.certtypebit", "La comprobaci\u00f3n de bits de tipo netscape ha fallado en el certificado" },
	{ "trustdecider.check.basicconstraints.extensionvalue", "La comprobaci\u00f3n del valor de la extensi\u00f3n de netscape ha fallado en el certificado" },
	{ "trustdecider.check.basicconstraints.bitvalue", "La comprobaci\u00f3n del valor de los bits 5,6,7 de netscape ha fallado en el certificado" },
	{ "trustdecider.check.basicconstraints.enduser", "La comprobaci\u00f3n del usuario final como CA ha fallado en el certificado" },
	{ "trustdecider.check.basicconstraints.pathlength", "La comprobaci\u00f3n de restricciones de longitud de ruta ha fallado en el certificado" },
	{ "trustdecider.check.leafkeyusage.length", "La comprobaci\u00f3n del uso de la longitud de clave ha fallado en el certificado" },
	{ "trustdecider.check.leafkeyusage.digitalsignature", "La comprobaci\u00f3n de la firma digital ha fallado en el certificado" },
	{ "trustdecider.check.leafkeyusage.extkeyusageinfo", "La comprobaci\u00f3n de informaci\u00f3n sobre el uso de la clave de extensi\u00f3n ha fallado en el certificado" },
	{ "trustdecider.check.leafkeyusage.certtypebit", "La comprobaci\u00f3n de bits de tipo netscape ha fallado en el certificado" },
	{ "trustdecider.check.signerkeyusage.lengthandbit", "La comprobaci\u00f3n de longitud y bit ha fallado en el certificado" },
	{ "trustdecider.check.signerkeyusage.keyusage", "La comprobaci\u00f3n del uso de claves ha fallado en el certificado" },
{ "trustdecider.check.canonicalize.updatecert", "Actualizar certificado ra\u00edz con certificado del archivo de certificados CA" },
{ "trustdecider.check.canonicalize.missing", "Agregar certificado ra\u00edz que falta" },
{ "trustdecider.check.gettrustedcert.find", "Buscar el CA de ra\u00edz v\u00e1lida en el archivo de certificados CA" },
{ "trustdecider.check.gettrustedissuercert.find", "Buscar el CA de ra\u00edz v\u00e1lida que falta en el archivo de certificados CA" },
    { "trustdecider.user.grant.session", "El usuario ha concedido privilegios de c\u00f3digo s\u00f3lo para esta sesi\u00f3n" },
    { "trustdecider.user.grant.forever", "El usuario ha concedido privilegios permanentes de c\u00f3digo" },
    { "trustdecider.user.deny", "El usuario ha denegado los privilegios de c\u00f3digo" },
    { "trustdecider.automation.trustcert", "Automatizaci\u00f3n: Confiar en el certificado RSA para la firma" },
    { "x509trustmgr.automation.ignoreclientcert", "Automatizaci\u00f3n: Ignorar certificado de cliente que no sea de confianza" },
    { "x509trustmgr.automation.ignoreservercert", "Automatizaci\u00f3n: Ignorar certificado de servidor que no sea de confianza" },

    { "appletcontext.audio.loaded", "Clip de audio cargado: {0}" },
    { "appletcontext.image.loaded", "Imagen cargada:{0} " },

    { "securitymgr.automation.printing", "Automatizaci\u00f3n: Aceptar impresi\u00f3n" },

    { "classloaderinfo.referencing", "Referencia a cargador de clases: {0}, contador de referencia={1}" },
    { "classloaderinfo.releasing", "Liberaci\u00f3n de cargador de clases: {0}, contador de referencia={1}" },
    { "classloaderinfo.caching", "Colocaci\u00f3n del cargador de clases en antememoria: {0}" },
    { "classloaderinfo.cachesize", "Tama\u00f1o de la antememoria del cargador de clases actual: {0}" },
    { "classloaderinfo.num", "El n\u00famero de cargadores de clases colocados en antememoria es superior a {0}, sin referencia {1}" },

    { "trace.listener.added", "Receptor de rastreo agregado: {0}" },
    { "trace.listener.removed", "Receptor de rastreo eliminado: {0}" },

    { "cookiehandler.cache", "Antememoria de cookie: " },
    { "cookiehandler.server", "Servidor {0} solicitar definici\u00f3n de cookie con \"{1}\"" },
    { "cookiehandler.connect", "Conectar {0} con cookie \"{1}\"" },
    { "cookiehandler.ignore.setcookie", "Cookie no est\u00e1 disponible - omitir \"Definici\u00f3n de cookie\"" },
    { "cookiehandler.noservice", "Cookie no est\u00e1 disponible - utilice la antememoria para determinar \"Cookie\"" },

    { "jsobject.eval", "Evaluar {0} = {1}" },
    { "jsobject.call", "JSObject::llamar: nombre={0}, url={1}, permiso={2}" },
    { "jsobject.eval.url.permission", "JSObject::eval({0}), url={1}, permiso={2}" },
    { "jsobject.getMember", "JSObject::getMember: nombre={0}, url={1}, permiso={2}" },
    { "jsobject.setMember", "JSObject::setMember: nombre={0}, url={1}, permiso={2}" },
    { "jsobject.removeMember", "JSObject::removeMember: nombre={0}, url={1}, permiso={2}" },
    { "jsobject.getSlot", "JSObject::getSlot: {0}, url={1}, permiso={2}" },
    { "jsobject.setSlot", "JSObject::setSlot: ranura={0}, url={1}, permiso={2}" },

    { "applet_install.ok", "Instalaci\u00f3n de miniaplicaci\u00f3n terminada." },
    { "applet_install.fail", "Instalaci\u00f3n de miniaplicaci\u00f3n no satisfactoria." },

    { "optpkg.install.info", "Instalaci\u00f3n de paquete opcional {0}" },
    { "optpkg.install.fail", "Instalaci\u00f3n del paquete opcional no satisfactoria." },
    { "optpkg.install.ok", "Instalaci\u00f3n del paquete opcional realizada." },
    { "optpkg.install.automation", "Automatizaci\u00f3n: Aceptar instalaci\u00f3n del paquete opcional" },
    { "optpkg.install.granted", "El usuario ha concedido la descarga del paquete opcional, descargar desde {0}" },
    { "optpkg.install.deny", "El usuario no ha concedido la descarga del paquete opcional" },
    { "optpkg.install.begin", "Instalaci\u00f3n {0}" },
    { "optpkg.install.java.launch", "Lanzar el instalador de Java" },
    { "optpkg.install.java.launch.command", "Lanzar el instalador de Java a trav\u00e9s de {0}" },
    { "optpkg.install.native.launch", "Lanzar instalador nativo" },
    { "optpkg.install.native.launch.fail.0", "Imposible ejecutar {0}" },
    { "optpkg.install.native.launch.fail.1", "Acceso a {0} no satisfactorio" },
    { "optpkg.install.raw.launch", "Instalaci\u00f3n del paquete opcional b\u00e1sico" },
    { "optpkg.install.raw.copy", "Copiar el paquete opcional b\u00e1sico desde {0} en {1}" },
    { "optpkg.install.error.nomethod", "No se ha instalado el proveedor de ampliaci\u00f3n dependiente : no se puede obtener el "
                         + " m\u00e9todo addExtensionInstallationProvider" },
    { "optpkg.install.error.noclass", "No se ha instalado el proveedor de ampliaci\u00f3n dependiente : no se puede obtener la "
                     + "clase sun.misc.ExtensionDependency" },

    { "dialogfactory.user.selected", "Usuario seleccionado: {0}" },
    { "dialogfactory.user.typed", "Usuario escrito: {0}" },

    {"progress_dialog.downloading", "M\u00f3dulo: descargando..."},
    {"progress_dialog.dismiss_button", "Descartar"},
        {"progress_dialog.dismiss_button.acceleratorKey", new Integer(KeyEvent.VK_D)},
    {"progress_dialog.from", "desde"},

    {"applet_viewer.color_tag", "N\u00famero de componentes incorrecto en {0}"},

    {"progress_info.downloading", "Descarga de archivos JAR"},
    {"progress_bar.preload", "Carga previa de archivos JAR: {0}"},
    
    {"cache.size", "Tama\u00f1o de la antememoria: {0}"},
    {"cache.cleanup", "El tama\u00f1o de la antememoria es: {0} bytes, es necesario limpiarla"},
    {"cache.full", "La antememoria est\u00e1 completa: supresi\u00f3n del archivo {0}"},
    {"cache.inuse", "No se puede suprimir el archivo {0} porque se est\u00e1 utilizando en esta aplicaci\u00f3n"},
    {"cache.notdeleted", "No se puede suprimir el archivo {0}, puede que se utilice en esta y/o otras aplicaciones"},
    {"cache.out_of_date", "La copia de {0} guardada en antememoria est\u00e1 caducada\n  Copia guardada en antememoria: {1}\n  Copia del servidor: {2}"},
    {"cache.loading", "Carga de {0} desde la antememoria"},
    {"cache.cache_warning", "ADVERTENCIA: no se puede guardar {0} en la antememoria"},
    {"cache.downloading", "Descarga de {0} a la antememoria"},
    {"cache.cached_name", "Nombre de archivo guardado en antememoria: {0}"},
    {"cache.load_warning", "ADVERTENCIA: error al leer {0} de la antememoria."},
    {"cache.disabled", "Antememoria inhabilitada por usuario"},
    {"cache.minSize", "Antememoria inhabilitada, el l\u00edmite de la antememoria es {0}, debe especificarse al menos 5 MB "},
    {"cache.directory_warning", "ADVERTENCIA: {0} no es un directorio. Se inhabilitar\u00e1 la antememoria."},
    {"cache.response_warning", "ADVERTENCIA: Respuesta inesperada {0} para {1}.  El archivo se descargar\u00e1 de nuevo."},
    {"cache.enabled", "Antememoria habilitada"},
    {"cache.location", "Ubicaci\u00f3n: {0}"},
    {"cache.maxSize", "Tama\u00f1o m\u00e1ximo: {0}"},
    {"cache.create_warning", "ADVERTENCIA: no ha sido posible crear el directorio {0} de la antememoria. se inhabilitar\u00e1 la colocaci\u00f3n en antememoria."},
    {"cache.read_warning", "ADVERTENCIA: no se puede leer el directorio {0} de la antememoria. se inhabilitar\u00e1 la colocaci\u00f3n en antememoria."},
    {"cache.write_warning", "ADVERTENCIA: no se puede escribir en el directorio {0} de la antememoria. se inhabilitar\u00e1 la colocaci\u00f3n en antememoria."},
    {"cache.compression", "Nivel de compresi\u00f3n: {0}"},
    {"cache.cert_load", "Los certificados para {0} se leen desde la antememoria JAR"},
    {"cache.jarjar.invalid_file", "el archivo .jarjar contiene un archivo distinto del .jar"},
    {"cache.jarjar.multiple_jar", "el archivo .jarjar contiene m\u00e1s de un archivo .jar"},
    {"cache.version_checking", "Comprobaci\u00f3n de la versi\u00f3n de {0}, la versi\u00f3n especificada es {1}"},
    { "cache.preloading", "Carga previa del archivo {0}"},

	{ "cache_viewer.caption", "Detalles - Antememoria" },
    { "cache_viewer.refresh", "Renovar" },
	{ "cache_viewer.refresh.acceleratorKey", new Integer(KeyEvent.VK_R) },
    { "cache_viewer.remove", "Borrar" },
	{ "cache_viewer.remove.acceleratorKey", new Integer(KeyEvent.VK_B) },
    { "cache_viewer.close", "Cerrar" },
	{ "cache_viewer.close.acceleratorKey", new Integer(KeyEvent.VK_C) },
    { "cache_viewer.name", "Nombre" },
    { "cache_viewer.type", "Tipo" },
    { "cache_viewer.size", "Tama\u00f1o" },
    { "cache_viewer.modify_date", "\u00daltima modificaci\u00f3n" },
    { "cache_viewer.expiry_date", "Fecha de caducidad" },
    { "cache_viewer.url", "URL" },
    { "cache_viewer.version", "Versi\u00f3n" },
    { "cache_viewer.help.name", "Nombre de archivo guardado en antememoria" },
    { "cache_viewer.help.type", "Tipo de archivo guardado en antememoria" },
    { "cache_viewer.help.size", "Tama\u00f1o de archivo guardado en antememoria" },
    { "cache_viewer.help.modify_date", "Fecha de la \u00faltima modificaci\u00f3n de archivo" },
    { "cache_viewer.help.expiry_date", "Fecha de caducidad de archivo" },
    { "cache_viewer.help.url", "Descarga de URL de archivo" },
    { "cache_viewer.help.version", "Versiones de antememoria de archivo" },
	{ "cache_viewer.delete.text", "<html><b>El archivo se ha borrado</b></html>{0} tal vez est\u00e9 en uso.\n" },
	{ "cache_viewer.delete.caption", "Error - Antememoria" },
    { "cache_viewer.type.zip", "Jar" },
    { "cache_viewer.type.class", "Clase" },
    { "cache_viewer.type.wav", "Sonido Wav" },
    { "cache_viewer.type.au", "Sonido Au" },
    { "cache_viewer.type.gif", "Imagen Gif" },
    { "cache_viewer.type.jpg", "Imagen Jpeg" },

    { "net.proxy.loading.ie", "Cargando configuraci\u00f3n delegada desde Internet Explorer ..."},
    { "net.proxy.loading.ns", "Cargando configuraci\u00f3n delegada desde Netscape Navigator ..."},
    { "net.proxy.loading.userdef", "Cargando configuraci\u00f3n delegada definida por el usuario ..."},
    { "net.proxy.loading.direct", "Cargando configuraci\u00f3n delegada directa ..."},
    { "net.proxy.loading.manual", "Cargando configuraci\u00f3n delegada manual ..."},
    { "net.proxy.loading.auto",   "Cargando configuraci\u00f3n delegada autom\u00e1tica ..."},
    { "net.proxy.loading.browser",   "Cargando configuraci\u00f3n delegada del navegador ..."},
    { "net.proxy.loading.manual.error", "Imposible utilizar la configuraci\u00f3n delegada manual - retroceder a DIRECTA"},
    { "net.proxy.loading.auto.error", "Imposible utilizar la configuraci\u00f3n delegada autom\u00e1tica - retroceder a MANUAL"},
    { "net.proxy.loading.done", "Terminado."},
    { "net.proxy.browser.pref.read", "Leer archivo de preferencia de usuario en {0}"},
    { "net.proxy.browser.proxyEnable", "    Habilitar delegado: {0}"},
    { "net.proxy.browser.proxyList",     "    Lista de delegado: {0}"},
    { "net.proxy.browser.proxyOverride", "    Anular delegado: {0}"},
    { "net.proxy.browser.autoConfigURL", "    Configuraci\u00f3n de URL autom\u00e1tica: {0}"},
    { "net.proxy.browser.smartConfig", "Hacer un ping al servidor del proxy {0} en el puerto {1}"},
    { "net.proxy.browser.connectionException", "No se puede acceder al servidor del proxy {0} desde el puerto {1}"},
    { "net.proxy.ns6.regs.exception", "Error al leer el archivo de registro: {0}"},
    { "net.proxy.pattern.convert", "Convertir lista de delegados omitidos a expresi\u00f3n regular: "},
    { "net.proxy.pattern.convert.error", "Imposible convertir lista de delegados omitidos a expresi\u00f3n regular - ignorar"},
    { "net.proxy.auto.download.ins", "Descargar archivo INS desde {0}" },
    { "net.proxy.auto.download.js", "Descargar archivo delegado autom\u00e1ticamente desde {0}" },
    { "net.proxy.auto.result.error", "Imposible determinar valor de delegado desde evaluaci\u00f3n - retroceder a DIRECTA"},
    { "net.proxy.service.not_available", "Delegado no disponible para {0} - el delegado es DIRECT por omisi\u00f3n" },

    { "lifecycle.applet.found", "Se ha encontrado la miniaplicaci\u00f3n previa detenida desde la antememoria del ciclo de vida \u00fatil" },
    { "lifecycle.applet.support", "La miniaplicaci\u00f3n soporta el modelo de ciclo de vida \u00fatil heredado - a\u00f1adir miniaplicaci\u00f3n a la antememoria de ciclo de vida \u00fatil" },
    { "lifecycle.applet.cachefull", "La antememoria de ciclo de vida \u00fatil est\u00e1 completa - reducir las miniaplicaciones de uso menos reciente" },    

	{ "com.method.ambiguous", "Imposible seleccionar un m\u00e9todo, par\u00e1metros ambiguos." },
	{ "com.method.notexists", "{0} :no existe ese m\u00e9todo" },
	{ "com.notexists", "{0} :no existe ese m\u00e9todo/esa propiedad" },
	{ "com.method.invoke", "Invocando m\u00e9todo: {0}" },
	{ "com.method.jsinvoke", "Invocando m\u00e9todo JS: {0}" },
	{ "com.method.argsTypeInvalid", "Los par\u00e1metros no pueden convertirse en los tipos requeridos" },
	{ "com.method.argCountInvalid", "El n\u00famero de argumentos no es correcto" },
	{ "com.field.needsConversion", "Se requiere conversi\u00f3n: {0} --> {1}" },
	{ "com.field.typeInvalid", " no puede convertirse al tipo: {0}" },
	{ "com.field.get", "Obteniendo propiedad: {0}" },
	{ "com.field.set", "Definiendo propiedad: {0}" },

	{"about.java.version", "        Version"},
	{"about.prompt.info", "Para obtener m\u00e1s informaci\u00f3n visite "},
	{"about.home.link", "http://www.java.com"},
	{"about.option.close", "Cerrar"},
	{"about.option.close.acceleratorKey", new Integer(KeyEvent.VK_C) },
	{"about.legal.note", "Copyright 2003, Sun Microsystems, Inc. Reservados todos los derechos. " +
			     "Uso sujeto a los t\u00e9rminos de la licencia. El software de terceros, " +
			     "incluida la tecnolog\u00eda de fuentes, est\u00e1 protegido por la ley de copyright y con " +
			     "licencia de los distribuidores de Sun. Partes de Copyright Eastman Kodak Company 1992. " +
			     "Este producto incluye c\u00f3digo con licencia de RSA Data Security. Sun, Sun Microsystems, " +
			     "el logotipo de Sun, Java, Solaris y J2SE son marcas comerciales o marcas comerciales " +
			     "registradas de Sun Microsystems, Inc. en los EE.UU. y en otros pa\u00edses. " +
			     "Todas las marcas registradas SPARC se usan bajo licencia y son marcas " +
			     "comerciales o marcas comerciales registradas de SPARC International, " +
			     "Inc. en los EE.UU. y en otros pa\u00edses. Adquisiciones federales: El software " +
			     "comercial y los usuarios del gobierno est\u00e1n sujetos a los t\u00e9rminos y condiciones " +
			     "de licencia est\u00e1ndar."}
 

   };
}


