#
# @(#)Makefile	1.16 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# @(#)Makefile	1.16 03/01/23
#
# Makefile for building the JDWP generator
#

BUILDDIR = ../..
PACKAGE = com.sun.tools.jdwpgen
PRODUCT = jpda
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
include FILES_java.gmk

#
# Rules.
#

include $(BUILDDIR)/common/Classes.gmk
