#
# @(#)Makefile	1.22 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the Notepad demo.
#

BUILDDIR = ../../..
DEMONAME = Notepad
include ../DemoSwing.gmk
