#
# @(#)Makefile	1.11 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Create 1.1 version of BeanInfo files needed by Swing.
#
# Note that this makefile gets visited only during release engineering
# time.
#

BUILDDIR = ../../..
include $(BUILDDIR)/common/Defs.gmk
include SwingBeans.gmk

all optimized debug: swing-1.2-beans

