#
# @(#)Makefile	1.6 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build applet demo.
#

BUILDDIR = ../../..
DEMONAME = BarChart
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(DEMODST)/BarChart.java
DEMO_dirs  = $(DEMODST)
DEMO_other = $(DEMODST)/example1.html
include ../DemoApplets.gmk

