/*
 * @(#)Resources_es.java	1.6 03/01/23
 *
 * Copyright 2003 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package sun.security.util;

/**
 * <p> This class represents the <code>ResourceBundle</code>
 * for KeyTool,PolicyTool and javax.security.auth.*.
 *
 * @version 1.11, 01/30/01
 */
public class Resources_es extends java.util.ListResourceBundle {

    private static final Object[][] contents = {

	// shared (from jarsigner)
	{" ", " "},
	{"  ", "  "},
	{"      ", "      "},
	{", ", ", "},
	// shared (from keytool)
	{"\n", "\n"},
	{"*******************************************",
		"*******************************************"},
	{"*******************************************\n\n",
		"*******************************************\n\n"},

	// keytool
	{"keytool error: ", "error de keytool: "},
	{"Illegal option:  ", "Opci\u00F3n no permitida:  "},
	{"Validity must be greater than zero",
		"La validez debe ser mayor que cero"},
	{"provName not a provider", "{0} no es un proveedor"},
	{"Must not specify both -v and -rfc with 'list' command",
		"No se deben especificar -v y -rfc simult\u00E1neamente con el comando 'list'"},
	{"Key password must be at least 6 characters",
		"La contrase\u00F1a clave debe tener al menos 6 caracteres"},
	{"New password must be at least 6 characters",
		"La nueva contrase\u00F1a debe tener al menos 6 caracteres"},
	{"Keystore file exists, but is empty: ",
		"El archivo de almac\u00E9n de claves existe, pero est\u00E1 vac\u00EDo "},
	{"Keystore file does not exist: ",
		"El archivo de almac\u00E9n de claves no existe: "},
	{"Must specify destination alias", "Se debe especificar alias de destino"},
	{"Must specify alias", "Se debe especificar alias"},
	{"Keystore password must be at least 6 characters",
		"La contrase\u00F1a del almac\u00E9n de claves debe tener al menos 6 caracteres"},
	{"Enter keystore password:  ", "Escriba la contrase\u00F1a del almac\u00E9n de claves:  "},
	{"Keystore password is too short - must be at least 6 characters",
	 "La contrase\u00F1a del almac\u00E9n de claves es demasiado corta, debe tener al menos 6 caracteres"},
	{"Too many failures - try later", "Demasiados fallos; int\u00E9ntelo m\u00E1s adelante"},
	{"Certification request stored in file <filename>",
		"Solicitud de certificaci\u00F3n almacenada en el archivo <{0}>"},
	{"Submit this to your CA", "Enviar a la CA"},
	{"Certificate stored in file <filename>",
		"Certificado almacenado en el archivo <{0}>"},
	{"Certificate reply was installed in keystore",
		"Se ha instalado la respuesta del certificado en el almac\u00E9n de claves"},
	{"Certificate reply was not installed in keystore",
		"No se ha instalado la respuesta del certificado en el almac\u00E9n de claves"},
	{"Certificate was added to keystore",
		"Se ha a\u00F1adido el certificado al almac\u00E9n de claves"},
	{"Certificate was not added to keystore",
		"No se ha a\u00F1adido el certificado al almac\u00E9n de claves"},
	{"[Saving ksfname]", "[Guardando {0}]"},
	{"alias has no public key (certificate)",
		"{0} no tiene clave p\u00FAblica (certificado)"},
	{"Cannot derive signature algorithm",
		"No se puede derivar el algoritmo de firma"},
	{"Alias <alias> does not exist",
		"El alias <{0}> no existe"},
	{"Alias <alias> has no certificate",
		"El alias <{0}> no tiene certificado"},
	{"Key pair not generated, alias <alias> already exists",
		"No se ha generado el par de claves, el alias <{0}> ya existe"},
	{"Cannot derive signature algorithm",
		"No se puede derivar el algoritmo de firma"},
	{"Generating keysize bit keyAlgName key pair and self-signed certificate (sigAlgName)\n\tfor: x500Name",
		"Generando bit {0} par de claves {1} y certificado autofirmado ({2})\n\tpara: {3}"},
	{"Enter key password for <alias>", "Escriba la contrase\u00F1a clave para <{0}>"},
	{"\t(RETURN if same as keystore password):  ",
		"\t(INTRO si es la misma contrase\u00F1a que la del almac\u00E9n de claves):  "},
	{"Key password is too short - must be at least 6 characters",
		"La contrase\u00F1a clave es demasiado corta; debe tener al menos 6 caracteres"},
	{"Too many failures - key not added to keystore",
		"Demasiados fallos; no se ha agregado la clave al almac\u00E9n de claves"},
	{"Destination alias <dest> already exists",
		"El alias de destino <{0}> ya existe"},
	{"Password is too short - must be at least 6 characters",
		"La contrase\u00F1a es demasiado corta; debe tener al menos 6 caracteres"},
	{"Too many failures. Key entry not cloned",
		"Demasiados errores. No se ha copiado la entrada de clave"},
	{"key password for <alias>", "contrase\u00F1a clave para <{0}>"},
	{"Keystore entry for <id.getName()> already exists",
		"La entrada de almac\u00E9n de claves para <{0}> ya existe"},
	{"Creating keystore entry for <id.getName()> ...",
		"Creando entrada de almac\u00E9n de claves para <{0}> ..."},
	{"No entries from identity database added",
		"No se han agregado entradas de la base de datos de identidades"},
	{"Alias name: alias", "Nombre de alias: {0}"},
	{"Creation date: keyStore.getCreationDate(alias)",
		"Fecha de creaci\u00F3n: {0,date}"},
	{"alias, keyStore.getCreationDate(alias), ",
		"{0}, {1,date}, "},
	{"Entry type: keyEntry", "Tipo de entrada: keyEntry"},
	{"keyEntry,", "keyEntry,"},
	{"Certificate chain length: ", "Longitud de la cadena de certificado: "},
	{"Certificate[(i + 1)]:", "Certificado[{0,number,integer}]:"},
	{"Certificate fingerprint (MD5): ", "Huella digital de certificado (MD5): "},
	{"Entry type: trustedCertEntry\n", "Tipo de entrada: trustedCertEntry\n"},
	{"trustedCertEntry,", "trustedCertEntry,"},
	{"Keystore type: ", "Tipo de almac\u00E9n de claves: "},
	{"Keystore provider: ", "Proveedor de almac\u00E9n de claves: "},
	{"Your keystore contains keyStore.size() entry",
		"Su almac\u00E9n de claves contiene entrada {0,number,integer}"},
	{"Your keystore contains keyStore.size() entries",
		"Su almac\u00E9n de claves contiene {0,number,integer} entradas"},
	{"Failed to parse input", "Error al analizar la entrada"},
	{"Empty input", "Entrada vac\u00EDa"},
	{"Not X.509 certificate", "No es un certificado X.509"},
	{"Cannot derive signature algorithm",
		"No se puede derivar el algoritmo de firma"},
	{"alias has no public key", "{0} no tiene clave p\u00FAblica"},
	{"alias has no X.509 certificate", "{0} no tiene certificado X.509"},
	{"New certificate (self-signed):", "Nuevo certificado (autofirmado):"},
	{"Reply has no certificates", "La respuesta no tiene certificados"},
	{"Certificate not imported, alias <alias> already exists",
		"Certificado no importado, el alias <{0}> ya existe"},
	{"Input not an X.509 certificate", "La entrada no es un certificado X.509"},
	{"Certificate already exists in keystore under alias <trustalias>",
		"El certificado ya existe en el almac\u00E9n de claves con el alias <{0}>"},
	{"Do you still want to add it? [no]:  ",
		"\u00BFA\u00FAn desea agregarlo? [no]:  "},
	{"Certificate already exists in system-wide CA keystore under alias <trustalias>",
		"El certificado ya existe en el almac\u00E9n de claves de la CA del sistema, con el alias <{0}>"},
	{"Do you still want to add it to your own keystore? [no]:  ",
		"\u00BFA\u00FAn desea agregarlo a su propio almac\u00E9n de claves? [no]:  "},
	{"Trust this certificate? [no]:  ", "\u00BFConfiar en este certificado? [no]:  "},
	{"YES", "S\u00CD"},
	{"New prompt: ", "Nuevo {0}: "},
	{"Passwords must differ", "Las contrase\u00F1as deben ser distintas"},
	{"Re-enter new prompt: ", "Vuelva a escribir el nuevo {0}: "},
	{"They don't match; try again", "No concuerdan; int\u00E9ntelo de nuevo"},
	{"Enter prompt alias name:  ", "Escriba el nombre de alias de {0}:  "},
	{"Enter alias name:  ", "Escriba el nombre de alias:  "},
	{"\t(RETURN if same as for <otherAlias>)",
		"\t(INTRO si es el mismo que para <{0}>)"},
	{"*PATTERN* printX509Cert",
		"Propietario: {0}\nEmisor: {1}\nN\u00FAmero de serie: {2}\nV\u00E1lido desde: {3} hasta: {4}\nHuellas digitales del certificado:\n\t MD5:  {5}\n\t SHA1: {6}"},
	{"What is your first and last name?",
		"\u00BFCu\u00E1les son su nombre y su apellido?"},
	{"What is the name of your organizational unit?",
		"\u00BFCu\u00E1l es el nombre de su unidad de organizaci\u00F3n?"},
	{"What is the name of your organization?",
		"\u00BFCu\u00E1l es el nombre de su organizaci\u00F3n?"},
	{"What is the name of your City or Locality?",
		"\u00BFCu\u00E1l es el nombre de su ciudad o localidad?"},
	{"What is the name of your State or Province?",
		"\u00BFCu\u00E1l es el nombre de su estado o provincia?"},
	{"What is the two-letter country code for this unit?",
		"\u00BFCu\u00E1l es el c\u00F3digo de pa\u00EDs de dos letras de la unidad?"},
	{"Is <name> correct?", "\u00BFEs correcto {0}?"},
	{"no", "no"},
	{"yes", "s\u00ED"},
	{"y", "y"},
	{"  [defaultValue]:  ", "  [{0}]:  "},
	{"Alias <alias> has no (private) key",
		"El alias <{0}> no tiene clave (privada)"},
	{"Recovered key is not a private key",
		"La clave recuperada no es una clave privada"},
	{"*****************  WARNING WARNING WARNING  *****************",
	    "*****************  ADVERTENCIA ADVERTENCIA ADVERTENCIA  *****************"},
	{"* The integrity of the information stored in your keystore  *",
	    "* La integridad de la informaci\u00F3n almacenada en su almac\u00E9n de claves  *"},
	{"* has NOT been verified!  In order to verify its integrity, *",
	    "* NO se ha comprobado. Para comprobar dicha integridad, *"},
	{"* you must provide your keystore password.                  *",
	    "deber\u00E1 proporcionar su contrase\u00F1a de almac\u00E9n de claves.                  *"},
	{"Certificate reply does not contain public key for <alias>",
		"La respuesta de certificado no contiene una clave p\u00FAblica para <{0}>"},
	{"Incomplete certificate chain in reply",
		"Cadena de certificado incompleta en la respuesta"},
	{"Certificate chain in reply does not verify: ",
		"La cadena de certificado de la respuesta no verifica: "},
	{"Top-level certificate in reply:\n",
		"Certificado de nivel superior en la respuesta:\n"},
	{"... is not trusted. ", "... no es de confianza. "},
	{"Install reply anyway? [no]:  ", "\u00BFinstalar respuesta de todos modos? [no]:  "},
	{"NO", "NO"},
	{"Public keys in reply and keystore don't match",
		"Las claves p\u00FAblicas en la respuesta y en el almac\u00E9n de claves no coinciden"},
	{"Certificate reply and certificate in keystore are identical",
		"La respuesta del certificado y el certificado en el almac\u00E9n de claves son id\u00E9nticos"},
	{"Failed to establish chain from reply",
		"No se ha podido establecer una cadena a partir de la respuesta"},
	{"n", "n"},
	{"Wrong answer, try again", "Respuesta incorrecta, vuelva a intentarlo"},
	{"keytool usage:\n", "sintaxis de keytool:\n"},
	{"-certreq     [-v] [-alias <alias>] [-sigalg <sigalg>]",
		"-certreq     [-v] [-alias <alias>] [-sigalg <algoritmo_firma>]"},
	{"\t     [-file <csr_file>] [-keypass <keypass>]",
		"\t     [-file <archivo_csr>] [-keypass <contrase\u00F1a_clave>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-delete      [-v] -alias <alias>",
		"-delete      [-v] -alias <alias>"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-export      [-v] [-rfc] [-alias <alias>] [-file <cert_file>]",
		"-export      [-v] [-rfc] [-alias <alias>] [-file <archivo_certif>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-genkey      [-v] [-alias <alias>] [-keyalg <keyalg>]",
		"-genkey      [-v] [-alias <alias>] [-keyalg <algoritmo_clave>]"},
	{"\t     [-keysize <keysize>] [-sigalg <sigalg>]",
		"\t     [-keysize <tama\u00F1o_clave>] [-sigalg <algoritmo_firma>]"},
	{"\t     [-dname <dname>] [-validity <valDays>]",
		"\t     [-dname <nombre_d>] [-validity <d\u00EDas_validez>]"},
	{"\t     [-keypass <keypass>] [-keystore <keystore>]",
		"\t     [-keypass <contrase\u00F1a_clave>] [-keystore <almac\u00E9n_claves>]"},
	{"\t     [-storepass <storepass>] [-storetype <storetype>]",
		"\t     [-storepass <contrase\u00F1a_almac\u00E9n>] [-storetype <tipo_almac\u00E9n>]"},
	{"\t     [-provider <provider_class_name>] ...",
		"\t     [-provider <nombre_clase_proveedor>] ..."},
	{"-help", "-help"},
	{"-identitydb  [-v] [-file <idb_file>] [-keystore <keystore>]",
		"-identitydb  [-v] [-file <archivo_idb>] [-keystore <almac\u00E9n_claves>]"},
	{"\t     [-storepass <storepass>] [-storetype <storetype>]",
		"\t     [-storepass <contrase\u00F1a_almac\u00E9n>] [-storetype <tipo_almac\u00E9n>]"},
	{"\t     [-provider <provider_class_name>] ...",
		"\t     [-provider <nombre_clase_proveedor>] ..."},
	{"-import      [-v] [-noprompt] [-trustcacerts] [-alias <alias>]",
		"-import      [-v] [-noprompt] [-trustcacerts] [-alias <alias>]"},
	{"\t     [-file <cert_file>] [-keypass <keypass>]",
		"\t     [-file <archivo_cert>] [-keypass <contrase\u00F1a_clave>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-keyclone    [-v] [-alias <alias>] -dest <dest_alias>",
		"-keyclone    [-v] [-alias <alias>] -dest <alias_destino>"},
	{"\t     [-keypass <keypass>] [-new <new_keypass>]",
		"\t     [-keypass <contrase\u00F1a_clave>] [-new <nueva_contrase\u00F1a_clave>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-keypasswd   [-v] [-alias <alias>]",
		"-keypasswd   [-v] [-alias <alias>]"},
	{"\t     [-keypass <old_keypass>] [-new <new_keypass>]",
		"\t     [-keypass <contrase\u00F1a_clave_antigua>] [-new <nueva_contrase\u00F1a_clave>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-list        [-v | -rfc] [-alias <alias>]",
		"-list        [-v | -rfc] [-alias <alias>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},
	{"-printcert   [-v] [-file <cert_file>]",
		"-printcert   [-v] [-file <archivo_certif>]"},
	{"-selfcert    [-v] [-alias <alias>] [-sigalg <sigalg>]",
		"-selfcert    [-v] [-alias <alias>] [-sigalg <algoritmo_firma>]"},
	{"\t     [-dname <dname>] [-validity <valDays>]",
		"\t     [-dname <nombre_d>] [-validity <d\u00EDas_validez>]"},
	{"\t     [-keypass <keypass>] [-keystore <keystore>]",
		"\t     [-keypass <contrase\u00F1a_clave>] [-keystore <almac\u00E9n_claves>]"},
	{"\t     [-storepass <storepass>] [-storetype <storetype>]",
		"\t     [-storepass <contrase\u00F1a_almac\u00E9n>] [-storetype <tipo_almac\u00E9n>]"},
	{"\t     [-provider <provider_class_name>] ...",
		"\t     [-provider <nombre_clase_proveedor>] ..."},
	{"-storepasswd [-v] [-new <new_storepass>]",
		"-storepasswd [-v] [-new <nueva_contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <almac\u00E9n_claves>] [-storepass <contrase\u00F1a_almac\u00E9n>]"},
	{"\t     [-storetype <storetype>] [-provider <provider_class_name>] ...",
		"\t     [-storetype <tipo_almac\u00E9n>] [-provider <nombre_clase_proveedor>] ..."},

	// policytool
	{"Warning: A public key for alias 'signers[i]' does not exist.",
		"Advertencia: No existe una clave p\u00FAblica para el alias {0}."},
	{"Warning: Class not found: ",
		"Advertencia: Clase no encontrada: "},
	{"Policy File opened successfully",
		"Archivo de normas abierto satisfactoriamente"},
	{"null Keystore name", "nombre de almac\u00E9n de claves nulo"},
	{"Warning: Unable to open Keystore: ",
		"Advertencia: No se puede abrir el almac\u00E9n de claves: "},
	{"Illegal option: ", "Opci\u00F3n no permitida: "},
	{"Usage: policytool [options]", "Sintaxis: policytool [opciones]"},
	{"  [-file <file>]    policy file location",
		"  [-file <archivo>]    ubicaci\u00F3n del archivo de normas"},
	{"New", "Nuevo"},
	{"Open", "Abrir"},
	{"Save", "Guardar"},
	{"Save As", "Guardar como"},
	{"View Warning Log", "Ver registro de advertencias"},
	{"Exit", "Salir"},
	{"Add Policy Entry", "Agregar entrada de norma"},
	{"Edit Policy Entry", "Editar entrada de norma"},
	{"Remove Policy Entry", "Eliminar entrada de norma"},
	{"Change KeyStore", "Cambiar almac\u00E9n de claves"},
	{"Add Public Key Alias", "Agregar alias de clave p\u00FAblico"},
	{"Remove Public Key Alias", "Eliminar alias de clave p\u00FAblico"},
	{"File", "Archivo"},
	{"Edit", "Editar"},
	{"Policy File:", "Archivo de normas:"},
	{"Keystore:", "Almac\u00E9n de claves:"},
	{"Error parsing policy file policyFile: pppe.getMessage()",
		"Error al analizar el archivo de normas {0}: {1}"},
	{"Could not find Policy File: ", "No se ha podido encontrar el archivo de normas: "},
	{"Policy Tool", "Herramienta de normas"},
	{"Errors have occurred while opening the policy configuration.  View the Warning Log for more information.",
		"Ha habido errores al abrir la configuraci\u00F3n de normas.  V\u00E9ase el registro de advertencias para obtener m\u00E1s informaci\u00F3n."},
	{"Error", "Error"},
	{"OK", "Aceptar"},
	{"Status", "Estado"},
	{"Warning", "Advertencia"},
	{"Permission:                                                       ",
		"Permiso:                                                       "},
	{"Target Name:                                                    ",
		"Nombre de destino:                                                    "},
	{"library name", "nombre de la biblioteca"},
	{"package name", "nombre del paquete"},
	{"property name", "nombre de la propiedad"},
	{"provider name", "nombre del proveedor"},
	{"Actions:                                                             ",
		"Acciones:                                                             "},
	{"OK to overwrite existing file filename?",
		"\u00BFSobrescribir el archivo existente {0}?"},
	{"Cancel", "Cancelar"},
	{"CodeBase:", "Base de c\u00F3digos:"},
	{"SignedBy:", "Firmado por:"},
	{"  Add Permission", "  Agregar permiso"},
	{"  Edit Permission", "  Editar permiso"},
	{"Remove Permission", "Eliminar permiso"},
	{"Done", "Terminar"},
	{"New KeyStore URL:", "URL de nuevo almac\u00E9n de claves:"},
	{"New KeyStore Type:", "Tipo de nuevo almac\u00E9n de claves:"},
	{"Permissions", "Permisos"},
	{"  Edit Permission:", "  Editar permiso:"},
	{"  Add New Permission:", "  Agregar permiso nuevo:"},
	{"Signed By:", "Firmado por:"},
	{"Permission and Target Name must have a value",
		"Permiso y Nombre de destino deben tener un valor"},
	{"Remove this Policy Entry?", "\u00BFEliminar esta entrada de norma?"},
	{"Overwrite File", "Sobrescribir archivo"},
	{"Policy successfully written to filename",
		"Norma escrita satisfactoriamente en {0}"},
	{"null filename", "nombre de archivo nulo"},
	{"filename not found", "{0} no encontrado"},
	{"     Save changes?", "     \u00BFGuardar cambios?"},
	{"Yes", "S\u00ED"},
	{"No", "No"},
	{"Error: Could not open policy file, filename, because of parsing error: pppe.getMessage()",
		"Error: No se ha podido abrir el archivo de normas, {0}, a causa de un error de an\u00E1lisis: {1}"},
	{"Permission could not be mapped to an appropriate class",
		"No se ha podido reasignar el permiso a una clase apropiada"},
	{"Policy Entry", "Entrada de norma"},
	{"Save Changes", "Guardar cambios"},
	{"No Policy Entry selected", "No se ha seleccionado entrada de norma"},
	{"Keystore", "Almac\u00E9n de claves"},
	{"KeyStore URL must have a valid value",
		"URL del almac\u00E9n de claves debe tener un valor v\u00E1lido"},
	{"Invalid value for Actions", "Valor no v\u00E1lido para Acciones"},
	{"No permission selected", "No se ha seleccionado un permiso"},
	{"Warning: Invalid argument(s) for constructor: ",
		"Advertencia: Argumentos no v\u00E1lidos para constructor: "},
	{"Add Principal", "Agregar principal"},
	{"Edit Principal", "Editar principal"},
	{"Remove Principal", "Eliminar principal"},
	{"Principal Type:", "Tipo de principal:"},
        {"Principal Name:", "Nombre de principal:"},
	{"Illegal Principal Type", "Tipo de principal no permitido"},
	{"No principal selected", "No se ha seleccionado principal"},
	{"Principals:", "Principales:"},
	{"Principals", "Principales"},
	{"  Add New Principal:", "  Agregar nuevo principal:"},
	{"  Edit Principal:", "  Editar principal:"},
	{"name", "nombre"},
	{"Cannot Specify Principal with a Wildcard Class without a Wildcard Name",
	    "No se puede especificar principal con una clase de comod\u00EDn sin un nombre de comod\u00EDn"},
	{"Cannot Specify Principal without a Class",
	    "No se puede especificar principal sin una clase"},

        {"Cannot Specify Principal without a Name",
            "No se puede especificar principal sin un nombre"},

	// javax.security.auth.PrivateCredentialPermission
	{"invalid null input(s)", "entradas nulas no v\u00E1lidas"},
	{"actions can only be 'read'", "las acciones s\u00F3lo pueden 'leerse'"},
	{"permission name [name] syntax invalid: ",
		"sintaxis de nombre de permiso [{0}] no v\u00E1lida: "},
	{"Credential Class not followed by a Principal Class and Name",
		"Clase de credencial no va seguida de una clase y nombre de principal"},
	{"Principal Class not followed by a Principal Name",
		"La clase de principal no va seguida de un nombre de principal"},
	{"Principal Name must be surrounded by quotes",
		"El nombre de principal debe ir entre comillas"},
	{"Principal Name missing end quote",
		"Faltan las comillas finales en el nombre de principal"},
	{"PrivateCredentialPermission Principal Class can not be a wildcard (*) value if Principal Name is not a wildcard (*) value",
		"La clase de principal PrivateCredentialPermission no puede ser un valor comod\u00EDn (*) si el nombre de principal no lo es tambi\u00E9n"},
	{"CredOwner:\n\tPrincipal Class = class\n\tPrincipal Name = name",
		"CredOwner:\n\tClase de principal = {0}\n\tNombre de principal = {1}"},

	// javax.security.auth.x500
	{"provided null name", "se ha proporcionado un nombre nulo"},

	// javax.security.auth.Subject
	{"invalid null AccessControlContext provided",
		"se ha proporcionado un AccessControlContext nulo no v\u00E1lido"},
	{"invalid null action provided", "se ha proporcionado una acci\u00F3n nula no v\u00E1lida"},
	{"invalid null Class provided", "se ha proporcionado una clase nula no v\u00E1lida"},
	{"Subject:\n", "Asunto:\n"},
	{"\tPrincipal: ", "\tPrincipal: "},
	{"\tPublic Credential: ", "\tCredencial p\u00FAblica: "},
	{"\tPrivate Credentials inaccessible\n",
		"\tCredenciales privadas inaccesibles\n"},
	{"\tPrivate Credential: ", "\tCredencial privada: "},
	{"\tPrivate Credential inaccessible\n",
		"\tCredencial privada inaccesible\n"},
	{"Subject is read-only", "El asunto es de s\u00F3lo lectura"},
	{"attempting to add an object which is not an instance of java.security.Principal to a Subject's Principal Set",
		"intentando agregar un objeto que no es un ejemplar de java.security.Principal al conjunto principal de un asunto"},
	{"attempting to add an object which is not an instance of class",
		"intentando agregar un objeto que no es un ejemplar de {0}"},

	// javax.security.auth.login.AppConfigurationEntry
	{"LoginModuleControlFlag: ", "LoginModuleControlFlag: "},

	// javax.security.auth.login.LoginContext
	{"Invalid null input: name", "Entrada nula no v\u00E1lida: nombre"},
	{"No LoginModules configured for name",
	 "No se han configurado LoginModules para {0}"},
	{"invalid null Subject provided", "se ha proporcionado un asunto nulo no v\u00E1lido"},
	{"invalid null CallbackHandler provided",
		"se ha proporcionado CallbackHandler nulo no v\u00E1lido"},
	{"null subject - logout called before login",
		"asunto nulo - se ha llamado a fin de sesi\u00F3n antes del inicio de sesi\u00F3n"},
	{"unable to instantiate LoginModule, module, because it does not provide a no-argument constructor",
		"no se puede lanzar un ejemplar de LoginModule, {0}, porque no incluye un constructor no-argumento"},
	{"unable to instantiate LoginModule",
		"no se puede lanzar un ejemplar de LoginModule"},
	{"unable to find LoginModule class: ",
		"no se puede encontrar la clase LoginModule: "},
	{"unable to access LoginModule: ",
		"no se puede acceder a LoginModule: "},
	{"Login Failure: all modules ignored",
		"Fallo en inicio de sesi\u00F3n: se ha hecho caso omiso de todos los m\u00F3dulos"},

	// sun.security.provider.PolicyFile

	{"java.security.policy: error parsing policy:\n\tmessage",
		"java.security.policy: error de an\u00E1lisis de {0}:\n\t{1}"},
	{"java.security.policy: error adding Permission, perm:\n\tmessage",
		"java.security.policy: error al agregar Permiso, {0}:\n\t{1}"},
	{"java.security.policy: error adding Entry:\n\tmessage",
		"java.security.policy: error al agregar Entrada:\n\t{0}"},
	{"alias name not provided (pe.name)", "no se ha proporcionado nombre de alias ({0})"},
	{"unable to perform substitution on alias, suffix",
		"no se puede realizar la sustituci\u00f3n en el alias, {0}"},
	{"substitution value, prefix, unsupported",
		"valor de sustituci\u00f3n, {0}, no soportado"},
	{"(", "("},
	{")", ")"},
	{"type can't be null","el tipo no puede ser nulo"},

	// sun.security.provider.PolicyParser
	{"expected keystore type", "se esperaba un tipo de almac\u00E9n de claves"},
	{"multiple Codebase expressions",
	        "expresiones m\u00FAltiples de base de c\u00F3digos"},
        {"multiple SignedBy expressions","expresiones m\u00FAltiples de SignedBy"},
	{"SignedBy has empty alias","SignedBy tiene un alias vac\u00EDo"},
	{"can not specify Principal with a wildcard class without a wildcard name",
		"no se puede especificar Principal con una clase de comod\u00EDn sin un nombre de comod\u00EDn"},
	{"expected codeBase or SignedBy or Principal",
		"se esperaba base de c\u00F3digos o SignedBy o Principal"},
	{"expected permission entry", "se esperaba un permiso de entrada"},
	{"number ", "n\u00FAmero "},
	{"expected [expect], read [end of file]",
		"se esperaba [{0}], se ha le\u00EDdo [end of file]"},
	{"expected [;], read [end of file]",
		"se esperaba [;], se ha le\u00EDdo [end of file]"},
	{"line number: msg", "l\u00EDnea {0}: {1}"},
	{"line number: expected [expect], found [actual]",
		"l\u00EDnea {0}: se esperaba [{1}], se ha encontrado [{2}]"},
	{"null principalClass or principalName",
		"principalClass o principalName nulos"},

	/* --- DEPRECATED --- */
	// javax.security.auth.Policy
	{"unable to instantiate Subject-based policy",
		"no se puede lanzar un ejemplar de la norma basada en Asunto"}
    };


    /**
     * Returns the contents of this <code>ResourceBundle</code>.
     *
     * <p>
     *
     * @return the contents of this <code>ResourceBundle</code>.
     */
    public Object[][] getContents() {
	return contents;
    }
}


