C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\JavaArray.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\Object.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\String.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\Comparable.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\CharSequence.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\Comparator.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\Math.java
C:\Dokumente und Einstellungen\Gerhard Hohner\jbproject\Equation\src\equation\Exception.java
***
