#
# @(#)Makefile	1.17 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../..

PACKAGE = java.math
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
FILES_java = \
	java/math/BigInteger.java \
        java/math/MutableBigInteger.java \
        java/math/SignedMutableBigInteger.java \
        java/math/BitSieve.java \
        java/math/BigDecimal.java

FILES_export = \
	java/math/BigInteger.java \
	java/math/BigDecimal.java

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
