#
# @(#)Makefile	1.9 03/01/23
#
# Copyright 2003 Sun Microsystems, Inc. All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# @(#)Makefile	1.9 03/01/23
#
# Makefile for building keytool utility.
#

BUILDDIR = ../../..
PACKAGE = sun.security.tools
PRODUCT = sun
PROGRAM = keytool
JAVA_ARGS = "{ \"-J-ms8m\", \"sun.security.tools.KeyTool\" }"
include $(BUILDDIR)/common/Defs.gmk

#
# Rules.
#
include $(BUILDDIR)/common/Program.gmk
